# Generated by Django 4.2.5 on 2023-10-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_date_of_employment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'get_latest_by': 'date_of_employment'},
        ),
    ]
