# Generated by Django 4.2.5 on 2023-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_namelist_name_alter_namelist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hobby',
            field=models.CharField(default='Gaming', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Other', 'Other')], default='Married', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(default='US', max_length=100),
        ),
    ]
