# Generated by Django 4.2.5 on 2023-11-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_hobby_customuser_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hobby',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
