# Generated by Django 4.2.5 on 2023-11-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_allergy_electricitybill_hospitalstaff_waterbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='date_issued',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='date_issued',
            field=models.DateField(unique=True),
        ),
    ]
