# Generated by Django 4.2.5 on 2023-11-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_electricitybill_date_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prescription_required', models.BooleanField(default=False)),
                ('package', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=100)),
                ('composition', models.CharField(max_length=1000)),
            ],
        ),
    ]
