from typing import Any
from django.core.management.base import BaseCommand, CommandError
from backbone.models import Degree, Specialist


class Command(BaseCommand):
    help = 'Populate the database with initial specialist data'

    def handle(self, *args: Any, **options: Any) -> str | None:
        medical_specialists = [
            "Family practice physician",
            "Internal medicine physician",
            "Pediatricians",
            "Geriatric medicine doctors",
            "Allergists",
            "Dermatologists",
            "Infectious disease doctors",
            "Ophthalmologists",
            "Obstetrician/gynecologists",
            "Cardiologists",
            "Endocrinologists",
            "Gastroenterologists",
            "Nephrologists",
            "Urologists",
            "Pulmonologists",
            "Otolaryngologists",
            "Neurologists",
            "Psychiatrists",
            "Oncologists",
            "Radiologists",
            "Rheumatologists",
            "General surgeons",
            "Orthopedic surgeons",
            "Cardiac surgeons",
            "Anesthesiologists",
            "Family medicine",
            "Internal Medicine",
            "Pediatrician",
            "Obstetricians/gynecologist (OBGYNs)",
            "Cardiologist",
            "Oncologist",
            "Gastroenterologist",
            "Pulmonologist",
            "Infectious disease",
            "Nephrologist",
            "Endocrinologist",
            "Ophthalmologist",
            "Otolaryngologist",
            "Dermatologist",
            "Psychiatrist",
            "Neurologist",
            "Radiologist",
            "Anesthesiologist",
            "Surgeon",
            "Physician executive",
            "Addiction medicine specialist",
            "Adolescent medicine specialist",
            "Allergist (immunologist)",
            "Anatomic pathologist",
            "Cardiac electrophysiologist",
            "Cardiovascular surgeon",
            "Clinical laboratory immunologist",
            "Colon and rectal surgeon",
            "Critical care medicine specialist",
            "Cytopathologist",
            "Dermatopathologist",
            "Developmental pediatrician",
            "Emergency medicine specialist",
            "Endocrinologist",
            "Forensic pathologist",
            "Gastroenterologist",
            "Geriatric psychiatrist",
            "Hand surgeon",
            "Hematologist",
            "Hepatologist",
            "Hospitalist",
            "Hyperbaric physician",
            "Infectious disease specialist",
            "Interventional cardiologist",
            "Medical examiner",
            "Medical geneticist",
            "Neonatologist",
            "Nephrologist",
            "Neurodevelopmental pediatrician",
            "Neurological surgeon",
            "Neuromusculoskeletal medicine doctor",
            "Neuropathologist",
            "Neuroradiologist",
            "Nuclear medicine specialist",
            "Obstetrician",
            "Occupational medicine specialist",
            "Orthopedic surgeon",
            "Otolaryngologist (head and neck surgeon)",
            "Pain management specialist",
            "Palliative medicine specialist",
            "Pathologist",
            "Pediatric allergist",
            "Pediatric cardiologist",
            "Pediatric endocrinologist",
            "Pediatric gastroenterologist",
            "Pediatric hematologist",
            "Pediatric infectious disease specialist",
            "Pediatric nephrologist",
            "Pediatric pulmonologist",
            "Pediatric rheumatologist",
            "Pediatric surgeon",
            "Pediatric urologist",
            "Perinatologist",
            "Physical medicine and rehabilitation specialist",
            "Plastic surgeon",
            "Preventive medicine specialist",
            "Psychiatrist (child and adolescent)",
            "Pulmonologist",
            "Radiation oncologist",
            "Reproductive endocrinologist",
            "Rheumatologist",
            "Sleep disorders specialist",
            "Spinal cord injury specialist",
            "Sports medicine specialist",
            "Surgical pathologist",
            "Thoracic surgeon",
            "Transplant hepatologist",
            "Trauma surgeon",
            "Urologist",
            "Vascular and interventional radiologist",
            "Vascular surgeon"
        ]
        try:
            medical_specialists = set(medical_specialists)
            medical_specialists_objects = [Specialist(name=special)
                                           for special in medical_specialists]
            Specialist.objects.bulk_create(medical_specialists_objects)
        except Exception as e:
            raise CommandError(f"Error occured: {e}")
        self.stdout.write(self.style.SUCCESS(
            f'Successfully added {Specialist.objects.count()} users!'))
