from django.core.management.base import BaseCommand
from accounts.models import Allergy  # Replace 'myapp' with your actual app name

class Command(BaseCommand):
    help = 'Populates the database with allergy data'

    def handle(self, *args, **kwargs):
        allergies = [
                "Peanut allergy",
                "Shellfish allergy",
                "Milk allergy",
                "Egg allergy",
                "Soy allergy",
                "Wheat allergy",
                "Tree nut allergy",
                "Fish allergy",
                "Sesame allergy",
                "Mustard allergy",
                "Latex allergy",
                "Pollen allergy",
                "Dust mite allergy",
                "Cat dander allergy",
                "Dog dander allergy",
                "Mold allergy",
                "Insect sting allergy",
                "Penicillin allergy",
                "Sulfa drug allergy",
                "Aspirin allergy",
                "Antibiotic allergy",
                "Dairy allergy",
                "Gluten allergy",
                "Corn allergy",
                "Beeswax allergy",
                "Strawberry allergy",
                "Tomato allergy",
                "Shellac allergy",
                "Nickel allergy",
                "Sunscreen allergy",
                "Fragrance allergy",
                "Perfume allergy",
                "Nickle allergy",
                "Gold allergy",
                "Silver allergy",
                "Copper allergy",
                "Latex condom allergy",
                "Chlorine allergy",
                "Iodine allergy",
                "Sulfite allergy",
                "Cinnamon allergy",
                "Chocolate allergy",
                "Coffee allergy",
                "Tea allergy",
                "Red dye allergy",
                "Yellow dye allergy",
                "Blue dye allergy",
                "Green dye allergy",
                "Black dye allergy",
                "White dye allergy",
                "Orange dye allergy",
                "Brown dye allergy",
                "Purple dye allergy",
                "Pink dye allergy",
                "Gray dye allergy",
                "Food coloring allergy",
                "Preservative allergy",
                "Artificial flavor allergy",
                "Artificial sweetener allergy",
                "MSG allergy",
                "Nitrate allergy",
                "Nitrite allergy",
                "High-fructose corn syrup allergy",
                "Monosodium glutamate (MSG) allergy",
                "Sulfur dioxide allergy",
                "Aloe vera allergy",
                "Avocado allergy",
                "Banana allergy",
                "Citrus allergy",
                "Kiwi allergy",
                "Mango allergy",
                "Papaya allergy",
                "Pineapple allergy",
                "Peach allergy",
                "Plum allergy",
                "Cherry allergy",
                "Grape allergy",
                "Watermelon allergy",
                "Cucumber allergy",
                "Bell pepper allergy",
                "Carrot allergy",
                "Celery allergy",
                "Onion allergy",
                "Garlic allergy",
                "Potato allergy",
                "Eggplant allergy",
                "Zucchini allergy",
                "Spinach allergy",
                "Lettuce allergy",
                "Kale allergy",
                "Cabbage allergy",
                "Broccoli allergy",
                "Cauliflower allergy",
                "Brussels sprouts allergy",
                "Asparagus allergy",
                "Radish allergy",
                "Turnip allergy",
                "Beet allergy",
                "Sweet potato allergy",
                "Butternut squash allergy",
                "Pumpkin allergy",
                "Acorn squash allergy",
                "Cantaloupe allergy",
                "Honeydew allergy",
                "Olive allergy",
                "Coconut allergy",
                "Almond allergy",
                "Cashew allergy",
                "Pecan allergy",
                "Walnut allergy",
                "Hazelnut allergy",
                "Pistachio allergy",
                "Macadamia nut allergy",
                "Brazil nut allergy",
                "Sunflower seed allergy",
                "Flaxseed allergy",
                "Chia seed allergy",
                "Poppy seed allergy",
                "Sesame seed allergy",
                "Pumpkin seed allergy",
                "Quinoa allergy",
                "Buckwheat allergy",
                "Barley allergy",
                "Rye allergy",
                "Oat allergy",
                "Millet allergy",
                "Sorghum allergy",
                "Amaranth allergy",
                "Teff allergy",
                "Spelt allergy",
                "Farro allergy",
                "Kamut allergy",
                "Durum allergy",
                "Bread allergy",
                "Pasta allergy",
                "Rice allergy",
                "Couscous allergy",
                "Polenta allergy",
                "Masa allergy",
                "Tapioca allergy",
                "Arrowroot allergy",
                "Yam allergy",
                "Tartrazine allergy",
                "Benzoic acid allergy",
                "Sodium benzoate allergy",
                "Citric acid allergy",
                "Malic acid allergy",
                "Tartaric acid allergy",
                "Lactic acid allergy",
                "Calcium propionate allergy",
                "Potassium sorbate allergy",
                "Sodium nitrate allergy",
                "Sodium nitrite allergy",
                "BHA allergy",
                "BHT allergy",
                "TBHQ allergy",
                "Sulfuric acid allergy",
                "Acetic acid allergy",
                "Propionic acid allergy",
                "Sorbic acid allergy",
                "Butyric acid allergy",
                "Phosphoric acid allergy",
                "Olestra allergy",
                "Carrageenan allergy",
                "Guar gum allergy",
                "Xanthan gum allergy",
                "Agar-agar allergy",
                "Gellan gum allergy",
                "Caffeine allergy",
                "Alcohol allergy",
                "Tobacco allergy",
                "Nicotine allergy",
                "Cocaine allergy",
                "Heroin allergy",
                "Marijuana allergy",
                "Amphetamine allergy",
                "Methamphetamine allergy",
                "Hallucinogen allergy",
                "Caffeine allergy",
                "Alcohol allergy",
                "Tobacco allergy",
                "Nicotine allergy",
                "Cocaine allergy",
                "Heroin allergy",
                "Marijuana allergy",
                "Amphetamine allergy",
                "Methamphetamine allergy",
                "Hallucinogen allergy",
                "Antibiotic allergy",
                "Sulfa drug allergy",
                "Nonsteroidal anti-inflammatory drug (NSAID) allergy",
                "Aspirin allergy",
                "Acetaminophen allergy",
                "Opioid allergy",
                "Codeine allergy",
                "Morphine allergy",
                "Hydrocodone allergy",
                "Oxycodone allergy",
                "Ibuprofen allergy",
                "Naproxen allergy",
                "Celecoxib allergy",
                "Antihistamine allergy",
                "Decongestant allergy",
                "Corticosteroid allergy",
                "Insulin allergy",
                "Oral contraceptive allergy",
                "Estrogen allergy",
                "Progesterone allergy",
                "Testosterone allergy",
                "Antidepressant allergy",
                "Antipsychotic allergy",
                "Antianxiety medication allergy",
                "Antiepileptic drug allergy",
                "Antibacterial soap allergy",
                "Sunscreen allergy",
                "Detergent allergy",
                "Fabric softener allergy",
                "Perfume allergy",
                "Essential oil allergy",
                "Aromatherapy allergy",
                "Candle allergy",
                "Incense allergy",
                "Air freshener allergy",
                "Mold allergy",
                "Dust allergy",
                "Pet dander allergy",
                "Cockroach allergy",
                "Pollen allergy",
                "Grass allergy",
                "Tree allergy",
                "Weed allergy",
                "Ragweed allergy",
                "Hay fever allergy",
                "Insect sting allergy",
                "Bee allergy",
                "Wasp allergy",
                "Hornet allergy",
                "Fire ant allergy",
                "Mosquito allergy",
                "Bed bug allergy",
                "Flea allergy",
                "Tick allergy",
                "Chigger allergy",
                "Spider allergy",
                "Scorpion allergy",
                "Centipede allergy",
                "Millipede allergy",
                "Jellyfish allergy",
                "Sea anemone allergy",
                "Coral allergy",
                "Seafood allergy",
                "Shellfish allergy",
                "Crustacean allergy",
                "Mollusk allergy",
                "Fish allergy",
                "Salmon allergy",
                "Tuna allergy",
                "Cod allergy",
                "Haddock allergy",
                "Halibut allergy",
                "Sole allergy",
                "Snapper allergy",
                "Trout allergy",
                "Bass allergy",
                "Catfish allergy",
                "Sardine allergy",
                "Anchovy allergy",
                "Mackerel allergy",
                "Mahi-mahi allergy",
                "Swordfish allergy",
                "Shark allergy",
                "Crab allergy",
                "Lobster allergy",
                "Shrimp allergy",
                "Crayfish allergy",
                "Clam allergy",
                "Oyster allergy",
                "Mussel allergy",
                "Squid allergy",
                "Octopus allergy",
                "Cuttlefish allergy",
                "Abalone allergy",
                "Escargot allergy",
                "Alligator allergy",
                "Turtle allergy",
                "Snake allergy",
                "Kangaroo allergy",
                "Bison allergy",
                "Elk allergy",
                "Venison allergy",
                "Rabbit allergy",
                "Pheasant allergy",
                "Quail allergy",
                "Duck allergy",
                "Goose allergy",
                "Turkey allergy",
                "Chicken allergy",
                "Beef allergy",
                "Pork allergy",
                "Lamb allergy",
                "Venison allergy",
                "Buffalo allergy",
                "Veal allergy",
                "Mutton allergy",
                "Horse meat allergy",
                "Dog meat allergy",
                "Cat meat allergy",
                "Rat meat allergy",
                "Bat meat allergy",
                "Rodent meat allergy",
                "Insect allergy",
                "Grasshopper allergy",
                "Cricket allergy",
                "Locust allergy",
                "Mealworm allergy",
                "Silkworm allergy",
                "Ant allergy",
                "Termite allergy",
                "Cockroach allergy",
                "Bed bug allergy",
                "Flea allergy",
                "Tick allergy",
                "Chigger allergy",
                "Spider allergy",
                "Scorpion allergy",
                "Centipede allergy",
                "Millipede allergy",
                "Jellyfish allergy",
                "Sea anemone allergy",
                "Coral allergy",
                "Bee allergy",
                "Wasp allergy",
                "Hornet allergy",
                "Fire ant allergy",
                "Mosquito allergy",
                "Medication allergy",
                "Food additive allergy",
                "Food coloring allergy",
                "Preservative allergy",
                "Artificial flavor allergy",
                "Artificial sweetener allergy",
                "MSG allergy",
                "Nitrate allergy",
                "Nitrite allergy",
                "High-fructose corn syrup allergy",
                "Monosodium glutamate (MSG) allergy",
                "Sulfur dioxide allergy",
                "Aloe vera allergy",
                "Avocado allergy",
                "Banana allergy",
                "Citrus allergy",
                "Kiwi allergy",
                "Mango allergy",
                "Papaya allergy",
                "Pineapple allergy",
                "Peach allergy",
                "Plum allergy",
                "Cherry allergy",
                "Grape allergy",
                "Watermelon allergy",
                "Cucumber allergy",
                "Bell pepper allergy",
                "Carrot allergy",
                "Celery allergy",
                "Onion allergy",
                "Garlic allergy",
                "Potato allergy",
                "Eggplant allergy",
                "Zucchini allergy",
                "Spinach allergy",
                "Lettuce allergy",
                "Kale allergy",
                "Cabbage allergy",
                "Broccoli allergy",
                "Cauliflower allergy",
                "Brussels sprouts allergy",
                "Asparagus allergy",
                "Radish allergy",
                "Turnip allergy",
                "Beet allergy",
                "Sweet potato allergy",
                "Butternut squash allergy",
                "Pumpkin allergy",
                "Acorn squash allergy",
                "Cantaloupe allergy",
                "Honeydew allergy",
                "Olive allergy",
                "Coconut allergy",
                "Almond allergy",
                "Cashew allergy",
                "Pecan allergy",
                "Walnut allergy",
                "Hazelnut allergy",
                "Pistachio allergy",
                "Macadamia nut allergy",
                "Brazil nut allergy",
                "Sunflower seed allergy",
                "Flaxseed allergy",
                "Chia seed allergy",
                "Poppy seed allergy",
                "Sesame seed allergy",
                "Pumpkin seed allergy",
                "Quinoa allergy",
                "Buckwheat allergy",
                "Barley allergy",
                "Rye allergy",
                "Oat allergy"]
            

        for allergy in allergies:
            Allergy.objects.create(type=allergy)

        self.stdout.write(self.style.SUCCESS('Successfully populated allergies table'))
