from django.core.management.base import BaseCommand
from accounts.models import Diagnosis  # Replace 'myapp' with your actual app name

class Command(BaseCommand):
    help = 'Populates the database with medical diagnoses and their recommended specialists'

    def handle(self, *args, **kwargs):
        medical_diagnosis= {
        "Family Practice Physician": [
            "Upper respiratory infection",
            "Hypertension",
            "Type 2 diabetes",
            "High cholesterol",
            "Common cold",
            "Influenza (flu)",
            "Acute bronchitis",
            "Gastroenteritis",
            "Urinary tract infection (UTI)",
            "Sinusitis",
            "Allergic rhinitis",
            "Otitis media (ear infection)",
            "Conjunctivitis (pink eye)",
            "Migraines",
            "Back pain",
            "Anxiety",
            "Depression",
            "Thyroid disorders",
            "Osteoarthritis",
            "Asthma"
        ],
        "Internal Medicine Physician": [
            "Hypertension",
            "Type 2 diabetes",
            "High cholesterol",
            "Chronic kidney disease",
            "Heart failure",
            "Chronic obstructive pulmonary disease (COPD)",
            "Rheumatoid arthritis",
            "Inflammatory bowel disease (IBD)",
            "Hypothyroidism",
            "Gout",
            "Systemic lupus erythematosus (SLE)",
            "Peptic ulcer disease",
            "Hepatitis",
            "Anemia",
            "Atrial fibrillation",
            "Deep vein thrombosis (DVT)",
            "Pneumonia",
            "Osteoporosis",
            "Celiac disease",
            "Multiple sclerosis (MS)"
        ],
        "Pediatrician": [
            "Ear infection",
            "Upper respiratory infection",
            "Asthma",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Autism spectrum disorder",
            "Allergies",
            "Gastroenteritis",
            "Chickenpox",
            "Urinary tract infection (UTI)",
            "Strep throat",
            "Conjunctivitis (pink eye)",
            "Childhood obesity",
            "Eczema",
            "Croup",
            "Recurrent fevers",
            "Celiac disease",
            "Food allergies",
            "Tourette syndrome",
            "Type 1 diabetes",
            "Speech and language delays"
        ],
        "Geriatric Medicine Doctors": [
            "Osteoarthritis",
            "Hypertension",
            "Type 2 diabetes",
            "Alzheimer's disease",
            "Osteoporosis",
            "Depression",
            "Heart failure",
            "Chronic obstructive pulmonary disease (COPD)",
            "Stroke",
            "Falls and fractures",
            "Urinary incontinence",
            "Dementia",
            "Parkinson's disease",
            "Peripheral neuropathy",
            "Visual impairment",
            "Hearing loss",
            "Arthritis",
            "Anxiety",
            "Malnutrition",
            "Polypharmacy"
        ],
        "Allergists": [
            "Allergic rhinitis (hay fever)",
            "Asthma",
            "Food allergies",
            "Insect sting allergies",
            "Drug allergies",
            "Atopic dermatitis (eczema)",
            "Contact dermatitis",
            "Urticaria (hives)",
            "Anaphylaxis",
            "Allergic conjunctivitis",
            "Latex allergy",
            "Sinusitis",
            "Eosinophilic esophagitis",
            "Allergic bronchopulmonary aspergillosis",
            "Mastocytosis",
            "Rhinosinusitis",
            "Immunodeficiency disorders",
            "Patch testing for allergies",
            "Environmental allergies",
            "Exercise-induced allergies"
        ],
        "Dermatologists": [
            "Acne",
            "Psoriasis",
            "Eczema",
            "Contact dermatitis",
            "Skin cancer (melanoma, basal cell carcinoma, squamous cell carcinoma)",
            "Rosacea",
            "Warts",
            "Shingles",
            "Ringworm",
            "Melasma",
            "Actinic keratosis",
            "Lupus-related skin issues",
            "Vitiligo",
            "Hives",
            "Hair loss (alopecia)",
            "Nail disorders",
            "Cellulitis",
            "Fungal infections",
            "Herpes",
            "Hyperhidrosis (excessive sweating)"
        ],"Infectious Disease Doctors": [
            "Influenza (flu)",
            "Pneumonia",
            "Tuberculosis",
            "HIV/AIDS",
            "COVID-19",
            "Malaria",
            "Hepatitis B",
            "Hepatitis C",
            "Sexually transmitted infections (STIs)",
            "Urinary tract infections (UTIs)",
            "Bacterial infections",
            "Viral infections",
            "Fungal infections",
            "Parasitic infections",
            "Antibiotic-resistant infections",
            "Travel-related infections",
            "Vector-borne infections",
            "Zoonotic infections",
            "Nosocomial (hospital-acquired) infections",
            "Infections in immunocompromised individuals"
        ],
        "Ophthalmologists": [
            "Refractive errors (nearsightedness, farsightedness, astigmatism)",
            "Cataracts",
            "Glaucoma",
            "Macular degeneration",
            "Diabetic retinopathy",
            "Retinal detachment",
            "Conjunctivitis (pink eye)",
            "Strabismus (crossed eyes)",
            "Amblyopia (lazy eye)",
            "Blepharitis",
            "Keratitis",
            "Uveitis",
            "Corneal ulcers",
            "Ptosis (drooping eyelid)",
            "Retinitis pigmentosa",
            "Eye trauma",
            "Ocular tumors",
            "Eye infections",
            "Dry eye syndrome",
            "Neuro-ophthalmic disorders"
        ],
        "Obstetrician/Gynecologists": [
            "Pregnancy",
            "Labor and delivery",
            "Cesarean section (C-section)",
            "Vaginal birth after cesarean (VBAC)",
            "High-risk pregnancies",
            "Gestational diabetes",
            "Preeclampsia",
            "Postpartum depression",
            "Polycystic ovary syndrome (PCOS)",
            "Endometriosis",
            "Uterine fibroids",
            "Ovarian cysts",
            "Pelvic inflammatory disease (PID)",
            "Cervical dysplasia",
            "Menstrual disorders",
            "Pelvic pain",
            "Menopause",
            "Breast health",
            "Sexually transmitted infections (STIs)",
            "Family planning and contraception"
        ],
        "Cardiologists": [
            "Hypertension",
            "Coronary artery disease",
            "Heart attack (myocardial infarction)",
            "Heart failure",
            "Arrhythmias",
            "Atrial fibrillation",
            "Valvular heart disease",
            "Peripheral artery disease (PAD)",
            "High cholesterol",
            "Hypertrophic cardiomyopathy",
            "Rheumatic heart disease",
            "Cardiogenic shock",
            "Myocarditis",
            "Pericarditis",
            "Congenital heart defects",
            "Pulmonary hypertension",
            "Endocarditis",
            "Cardiac arrest",
            "Syncope (fainting)",
            "Preventive cardiology"
        ],
        "Endocrinologists": [
            "Diabetes mellitus",
            "Type 1 diabetes",
            "Type 2 diabetes",
            "Thyroid disorders (hypothyroidism, hyperthyroidism)",
            "Hashimoto's thyroiditis",
            "Graves' disease",
            "Adrenal disorders",
            "Cushing's syndrome",
            "Addison's disease",
            "Polycystic ovary syndrome (PCOS)",
            "Hirsutism",
            "Osteoporosis",
            "Pituitary disorders",
            "Acromegaly",
            "Gigantism",
            "Short stature",
            "Parathyroid disorders",
            "Hormonal imbalances",
            "Metabolic syndrome",
            "Lipid disorders"
        ],"Gastroenterologists": [
            "Gastroesophageal reflux disease (GERD)",
            "Peptic ulcer disease",
            "Inflammatory bowel disease (Crohn's disease, ulcerative colitis)",
            "Irritable bowel syndrome (IBS)",
            "Celiac disease",
            "Gastritis",
            "Gastroenteritis",
            "Liver cirrhosis",
            "Hepatitis (Hepatitis B, Hepatitis C)",
            "Gallstones",
            "Pancreatitis",
            "Colorectal cancer",
            "Diverticulitis",
            "Gastrointestinal bleeding",
            "Gastrointestinal perforation",
            "Eosinophilic esophagitis",
            "Barrett's esophagus",
            "Gastrointestinal motility disorders",
            "Small intestinal bacterial overgrowth (SIBO)",
            "Hemorrhoids"
        ],
        "Nephrologists": [
            "Chronic kidney disease (CKD)",
            "Acute kidney injury",
            "Hypertension-related kidney disease",
            "Glomerulonephritis",
            "Polycystic kidney disease (PKD)",
            "Kidney stones",
            "Urinary tract infections (UTIs)",
            "Nephrotic syndrome",
            "Renal artery stenosis",
            "Diabetic nephropathy",
            "Lupus nephritis",
            "Interstitial nephritis",
            "Renal cysts",
            "Hydronephrosis",
            "Renal cell carcinoma",
            "Hematuria (blood in urine)",
            "Proteinuria",
            "Electrolyte disorders",
            "Renal transplantation",
            "Acid-base imbalances"
        ],
        "Urologists": [
            "Urinary tract infections (UTIs)",
            "Kidney stones",
            "Bladder infections",
            "Prostate issues (benign prostatic hyperplasia, prostatitis)",
            "Erectile dysfunction",
            "Testicular cancer",
            "Bladder cancer",
            "Kidney cancer",
            "Urinary incontinence",
            "Overactive bladder",
            "Pelvic organ prolapse",
            "Urethral stricture",
            "Interstitial cystitis",
            "Varicocele",
            "Hydrocele",
            "Male infertility",
            "Sexual dysfunction",
            "Hematuria (blood in urine)",
            "Proteinuria",
            "Renal transplantation"
        ],
        "Pulmonologists": [
            "Asthma",
            "Chronic obstructive pulmonary disease (COPD)",
            "Pneumonia",
            "Bronchitis",
            "Interstitial lung disease",
            "Lung cancer",
            "Pulmonary embolism",
            "Tuberculosis",
            "Cystic fibrosis",
            "Pleural effusion",
            "Pulmonary fibrosis",
            "Sleep apnea",
            "Lung nodules",
            "Sarcoidosis",
            "Bronchiectasis",
            "Occupational lung diseases",
            "Pulmonary hypertension",
            "Respiratory distress syndrome (ARDS)",
            "Lung transplantation",
            "Pleural diseases"
        ],
        "Otolaryngologists": [
            "Sinusitis",
            "Tonsillitis",
            "Ear infections",
            "Hearing loss",
            "Balance disorders",
            "Tinnitus",
            "Meniere's disease",
            "Allergic rhinitis",
            "Nasal polyps",
            "Deviated septum",
            "Laryngitis",
            "Voice disorders",
            "Thyroid nodules",
            "Salivary gland disorders",
            "Head and neck cancers",
            "Facial trauma",
            "Snoring and sleep apnea",
            "Cleft lip and palate",
            "Swallowing disorders",
            "Temporal bone fractures"
        ],"Neurologists": [
            "Migraine",
            "Epilepsy",
            "Multiple sclerosis (MS)",
            "Parkinson's disease",
            "Alzheimer's disease",
            "Stroke",
            "Peripheral neuropathy",
            "Amyotrophic lateral sclerosis (ALS)",
            "Huntington's disease",
            "Trigeminal neuralgia",
            "Bell's palsy",
            "Neurodegenerative disorders",
            "Spinal cord injury",
            "Cerebral palsy",
            "Traumatic brain injury",
            "Restless legs syndrome",
            "Myasthenia gravis",
            "Neuropathic pain",
            "Neurogenetic disorders",
            "Narcolepsy"
        ],
        "Psychiatrists": [
            "Major depressive disorder",
            "Generalized anxiety disorder",
            "Bipolar disorder",
            "Schizophrenia",
            "Obsessive-compulsive disorder (OCD)",
            "Post-traumatic stress disorder (PTSD)",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Eating disorders (anorexia nervosa, bulimia nervosa)",
            "Panic disorder",
            "Social anxiety disorder",
            "Borderline personality disorder",
            "Dissociative disorders",
            "Substance use disorders",
            "Sleep disorders",
            "Autism spectrum disorder",
            "Mood disorders",
            "Psychotic disorders",
            "Personality disorders",
            "Adjustment disorders",
            "Sexual dysfunction"
        ],
        "Oncologists": [
            "Breast cancer",
            "Lung cancer",
            "Colorectal cancer",
            "Prostate cancer",
            "Ovarian cancer",
            "Leukemia",
            "Lymphoma",
            "Pancreatic cancer",
            "Liver cancer",
            "Kidney cancer",
            "Bladder cancer",
            "Gastrointestinal stromal tumor (GIST)",
            "Brain tumors",
            "Bone cancer",
            "Thyroid cancer",
            "Melanoma",
            "Testicular cancer",
            "Cervical cancer",
            "Uterine cancer",
            "Multiple myeloma"
        ],
        "Radiologists": [
            "X-ray interpretation",
            "Computed tomography (CT) scans",
            "Magnetic resonance imaging (MRI)",
            "Ultrasound imaging",
            "Positron emission tomography (PET) scans",
            "Fluoroscopy",
            "Mammography",
            "Interventional radiology procedures",
            "Nuclear medicine imaging",
            "Angiography",
            "Bone densitometry",
            "Breast imaging",
            "Cardiac imaging",
            "Neuroradiology",
            "Musculoskeletal radiology",
            "Abdominal imaging",
            "Thoracic imaging",
            "Pediatric radiology",
            "Emergency radiology",
            "Genitourinary radiology"
        ],
        "Rheumatologists": [
            "Rheumatoid arthritis",
            "Osteoarthritis",
            "Systemic lupus erythematosus (SLE)",
            "Sjögren's syndrome",
            "Ankylosing spondylitis",
            "Psoriatic arthritis",
            "Gout",
            "Polymyalgia rheumatica",
            "Systemic sclerosis (scleroderma)",
            "Vasculitis",
            "Fibromyalgia",
            "Juvenile idiopathic arthritis (JIA)",
            "Behçet's disease",
            "Polymyositis",
            "Dermatomyositis",
            "Mixed connective tissue disease",
            "Autoimmune hepatitis",
            "Sarcoidosis",
            "Inflammatory myopathies",
            "Antiphospholipid syndrome"
        ],
        "General Surgeons": [
            "Appendicitis",
            "Gallbladder disease",
            "Hernias",
            "Colorectal cancer",
            "Breast cancer",
            "Thyroid nodules",
            "Gastrointestinal bleeding",
            "Diverticulitis",
            "Gastroesophageal reflux disease (GERD)",
            "Pancreatitis",
            "Appendectomy",
            "Cholecystectomy",
            "Colectomy",
            "Mastectomy",
            "Hemorrhoidectomy",
            "Thyroidectomy",
            "Bariatric surgery",
            "Liver resection",
            "Lung resection",
            "Esophagectomy"
        ],"Orthopedic Surgeons": [
            "Fractures",
            "Osteoarthritis",
            "Rheumatoid arthritis",
            "ACL tear",
            "Meniscus tear",
            "Rotator cuff tear",
            "Carpal tunnel syndrome",
            "Herniated disc",
            "Spinal stenosis",
            "Scoliosis",
            "Bone tumors",
            "Tendonitis",
            "Bursitis",
            "Hip dysplasia",
            "Frozen shoulder",
            "Plantar fasciitis",
            "Dupuytren's contracture",
            "Ganglion cysts",
            "Ankle sprain",
            "Osteoporosis"
        ],
        "Cardiac Surgeons": [
            "Coronary artery disease",
            "Aortic aneurysm",
            "Valvular heart disease",
            "Congenital heart defects",
            "Heart failure",
            "Atrial fibrillation",
            "Mitral valve prolapse",
            "Ischemic heart disease",
            "Myocardial infarction (Heart attack)",
            "Cardiomyopathy",
            "Heart valve disease",
            "Coronary artery bypass grafting (CABG)",
            "Heart transplantation",
            "Aortic dissection",
            "Arrhythmias",
            "Atrial septal defect (ASD)",
            "Ventricular septal defect (VSD)",
            "Tricuspid atresia",
            "Tetralogy of Fallot",
            "Coarctation of the aorta"
        ],
        "Anesthesiologists": [
            "Anesthesia management for surgery",
            "Pain management",
            "Epidural injections",
            "Spinal anesthesia",
            "General anesthesia",
            "Local anesthesia",
            "Regional anesthesia",
            "Conscious sedation",
            "Intubation",
            "Ventilation management",
            "Intravenous (IV) anesthesia",
            "Anesthetic complications",
            "Postoperative pain control",
            "Chronic pain management",
            "Neuropathic pain",
            "Postherpetic neuralgia",
            "Cancer pain",
            "Fibromyalgia",
            "Complex regional pain syndrome (CRPS)",
            "Palliative care"
        ],
        "Family Medicine": [
            "Upper respiratory infections",
            "Hypertension",
            "Type 2 diabetes",
            "High cholesterol",
            "Common cold",
            "Influenza (flu)",
            "Acute bronchitis",
            "Gastroenteritis",
            "Urinary tract infection (UTI)",
            "Sinusitis",
            "Allergic rhinitis",
            "Otitis media (ear infection)",
            "Conjunctivitis (pink eye)",
            "Migraines",
            "Back pain",
            "Anxiety",
            "Depression",
            "Thyroid disorders",
            "Osteoarthritis",
            "Asthma"
        ],
        "Internal Medicine": [
            "Hypertension",
            "Type 2 diabetes",
            "High cholesterol",
            "Chronic kidney disease",
            "Heart failure",
            "Chronic obstructive pulmonary disease (COPD)",
            "Rheumatoid arthritis",
            "Inflammatory bowel disease (IBD)",
            "Hypothyroidism",
            "Gout",
            "Systemic lupus erythematosus (SLE)",
            "Peptic ulcer disease",
            "Hepatitis",
            "Anemia",
            "Atrial fibrillation",
            "Deep vein thrombosis (DVT)",
            "Pneumonia",
            "Osteoporosis",
            "Celiac disease",
            "Multiple sclerosis (MS)"
        ],
        "Pediatrician": [
            "Ear infection",
            "Upper respiratory infection",
            "Asthma",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Autism spectrum disorder",
            "Allergies",
            "Gastroenteritis",
            "Chickenpox",
            "Urinary tract infection (UTI)",
            "Strep throat",
            "Conjunctivitis (pink eye)",
            "Childhood obesity",
            "Eczema",
            "Croup",
            "Recurrent fevers",
            "Celiac disease",
            "Food allergies",
            "Tourette syndrome",
            "Type 1 diabetes",
            "Speech and language delays"
        ],
        "Obstetricians/Gynecologists (OBGYNs)": [
            "Pregnancy",
            "Labor and delivery",
            "Cesarean section (C-section)",
            "Vaginal birth after cesarean (VBAC)",
            "High-risk pregnancies",
            "Gestational diabetes",
            "Preeclampsia",
            "Postpartum depression",
            "Polycystic ovary syndrome (PCOS)",
            "Endometriosis",
            "Uterine fibroids",
            "Ovarian cysts",
            "Pelvic inflammatory disease (PID)",
            "Cervical dysplasia",
            "Menstrual disorders",
            "Pelvic pain",
            "Menopause",
            "Breast health",
            "Sexually transmitted infections (STIs)",
            "Family planning and contraception"
        ],"Cardiologist": [
            "Hypertension",
            "Coronary artery disease",
            "Heart attack (myocardial infarction)",
            "Heart failure",
            "Arrhythmias",
            "Atrial fibrillation",
            "Valvular heart disease",
            "Peripheral artery disease (PAD)",
            "High cholesterol",
            "Hypertrophic cardiomyopathy",
            "Rheumatic heart disease",
            "Cardiogenic shock",
            "Myocarditis",
            "Pericarditis",
            "Congenital heart defects",
            "Pulmonary hypertension",
            "Endocarditis",
            "Cardiac arrest",
            "Syncope (fainting)",
            "Preventive cardiology"
        ],
        "Oncologist": [
            "Breast cancer",
            "Lung cancer",
            "Colorectal cancer",
            "Prostate cancer",
            "Ovarian cancer",
            "Leukemia",
            "Lymphoma",
            "Pancreatic cancer",
            "Liver cancer",
            "Kidney cancer",
            "Bladder cancer",
            "Gastrointestinal stromal tumor (GIST)",
            "Brain tumors",
            "Bone cancer",
            "Thyroid cancer",
            "Melanoma",
            "Testicular cancer",
            "Cervical cancer",
            "Uterine cancer",
            "Multiple myeloma"
        ],
        "Gastroenterologist": [
            "Gastroesophageal reflux disease (GERD)",
            "Peptic ulcer disease",
            "Inflammatory bowel disease (Crohn's disease, ulcerative colitis)",
            "Irritable bowel syndrome (IBS)",
            "Celiac disease",
            "Gastritis",
            "Gastroenteritis",
            "Liver cirrhosis",
            "Hepatitis (Hepatitis B, Hepatitis C)",
            "Gallstones",
            "Pancreatitis",
            "Colorectal cancer",
            "Diverticulitis",
            "Gastrointestinal bleeding",
            "Gastrointestinal perforation",
            "Eosinophilic esophagitis",
            "Barrett's esophagus",
            "Gastrointestinal motility disorders",
            "Small intestinal bacterial overgrowth (SIBO)",
            "Hemorrhoids"
        ],
        "Pulmonologist": [
            "Asthma",
            "Chronic obstructive pulmonary disease (COPD)",
            "Pneumonia",
            "Bronchitis",
            "Interstitial lung disease",
            "Lung cancer",
            "Pulmonary embolism",
            "Tuberculosis",
            "Cystic fibrosis",
            "Pleural effusion",
            "Pulmonary fibrosis",
            "Sleep apnea",
            "Lung nodules",
            "Sarcoidosis",
            "Bronchiectasis",
            "Occupational lung diseases",
            "Pulmonary hypertension",
            "Respiratory distress syndrome (ARDS)",
            "Lung transplantation",
            "Pleural diseases"
        ],
        "Infectious Disease": [
            "Influenza (flu)",
            "Pneumonia",
            "Tuberculosis",
            "HIV/AIDS",
            "COVID-19",
            "Malaria",
            "Hepatitis B",
            "Hepatitis C",
            "Sexually transmitted infections (STIs)",
            "Urinary tract infections (UTIs)",
            "Bacterial infections",
            "Viral infections",
            "Fungal infections",
            "Parasitic infections",
            "Antibiotic-resistant infections",
            "Travel-related infections",
            "Vector-borne infections",
            "Zoonotic infections",
            "Nosocomial (hospital-acquired) infections",
            "Infections in immunocompromised individuals"
        ],
        "Nephrologist": [
            "Chronic kidney disease (CKD)",
            "Acute kidney injury",
            "Hypertension-related kidney disease",
            "Glomerulonephritis",
            "Polycystic kidney disease (PKD)",
            "Kidney stones",
            "Urinary tract infections (UTIs)",
            "Nephrotic syndrome",
            "Renal artery stenosis",
            "Diabetic nephropathy",
            "Lupus nephritis",
            "Interstitial nephritis",
            "Renal cysts",
            "Hydronephrosis",
            "Renal cell carcinoma",
            "Hematuria (blood in urine)",
            "Proteinuria",
            "Electrolyte disorders",
            "Renal transplantation",
            "Acid-base imbalances"
        ],
        "Endocrinologist": [
            "Diabetes mellitus",
            "Type 1 diabetes",
            "Type 2 diabetes",
            "Thyroid disorders (hypothyroidism, hyperthyroidism)",
            "Adrenal disorders (Cushing's syndrome, Addison's disease)",
            "Polycystic ovary syndrome (PCOS)",
            "Hormone disorders",
            "Osteoporosis",
            "Metabolic syndrome",
            "Pituitary disorders",
            "Growth hormone disorders",
            "Parathyroid disorders",
            "Calcium disorders",
            "Lipid disorders",
            "Menstrual disorders",
            "Hirsutism",
            "Infertility",
            "Pituitary tumors",
            "Thyroid cancer",
            "Endocrine hypertension"
        ],
        "Ophthalmologist": [
            "Cataracts",
            "Glaucoma",
            "Age-related macular degeneration (AMD)",
            "Diabetic retinopathy",
            "Retinal detachment",
            "Refractive errors (myopia, hyperopia, astigmatism)",
            "Conjunctivitis (pink eye)",
            "Dry eye syndrome",
            "Corneal diseases",
            "Uveitis",
            "Strabismus",
            "Amblyopia (lazy eye)",
            "Retinitis pigmentosa",
            "Keratoconus",
            "Macular edema",
            "Optic neuritis",
            "Retinal vein occlusion",
            "Ocular migraines",
            "Retinal tears",
            "Ocular hypertension"
        ],"Otolaryngologist": [
            "Otitis media (ear infection)",
            "Hearing loss",
            "Tinnitus",
            "Vertigo",
            "Sinusitis",
            "Nasal polyps",
            "Allergic rhinitis",
            "Deviated septum",
            "Sleep apnea",
            "Tonsillitis",
            "Adenoiditis",
            "Laryngitis",
            "Gastroesophageal reflux disease (GERD)",
            "Voice disorders",
            "Throat cancer",
            "Swallowing disorders",
            "Salivary gland disorders",
            "Temporomandibular joint (TMJ) disorders",
            "Head and neck tumors",
            "Facial plastic and reconstructive surgery"
        ],
        "Dermatologist": [
            "Acne",
            "Eczema",
            "Psoriasis",
            "Rosacea",
            "Contact dermatitis",
            "Melasma",
            "Vitiligo",
            "Hives (urticaria)",
            "Warts",
            "Skin infections (bacterial, fungal, viral)",
            "Moles and skin lesions",
            "Skin cancer (melanoma, basal cell carcinoma, squamous cell carcinoma)",
            "Atopic dermatitis",
            "Seborrheic dermatitis",
            "Hair loss (alopecia)",
            "Nail disorders",
            "Cysts and lipomas",
            "Sunburn",
            "Hyperhidrosis",
            "Connective tissue diseases affecting the skin"
        ],
        "Psychiatrist": [
            "Major depressive disorder",
            "Generalized anxiety disorder",
            "Bipolar disorder",
            "Schizophrenia",
            "Obsessive-compulsive disorder (OCD)",
            "Post-traumatic stress disorder (PTSD)",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Eating disorders (anorexia nervosa, bulimia nervosa)",
            "Panic disorder",
            "Social anxiety disorder",
            "Borderline personality disorder",
            "Dissociative disorders",
            "Substance use disorders",
            "Sleep disorders",
            "Autism spectrum disorder",
            "Mood disorders",
            "Psychotic disorders",
            "Personality disorders",
            "Adjustment disorders",
            "Sexual dysfunction"
        ],
        "Neurologist": [
            "Migraine",
            "Epilepsy",
            "Multiple sclerosis (MS)",
            "Parkinson's disease",
            "Alzheimer's disease",
            "Stroke",
            "Peripheral neuropathy",
            "Amyotrophic lateral sclerosis (ALS)",
            "Huntington's disease",
            "Trigeminal neuralgia",
            "Bell's palsy",
            "Neurodegenerative disorders",
            "Spinal cord injury",
            "Cerebral palsy",
            "Traumatic brain injury",
            "Restless legs syndrome",
            "Myasthenia gravis",
            "Neuropathic pain",
            "Neurogenetic disorders",
            "Narcolepsy"
        ],
        "Radiologist": [
            "X-ray interpretation",
            "Computed tomography (CT) scans",
            "Magnetic resonance imaging (MRI)",
            "Ultrasound imaging",
            "Positron emission tomography (PET) scans",
            "Fluoroscopy",
            "Mammography",
            "Interventional radiology procedures",
            "Nuclear medicine imaging",
            "Angiography",
            "Bone densitometry",
            "Breast imaging",
            "Cardiac imaging",
            "Neuroradiology",
            "Musculoskeletal radiology",
            "Abdominal imaging",
            "Thoracic imaging",
            "Pediatric radiology",
            "Emergency radiology",
            "Genitourinary radiology"
        ],
        "Anesthesiologist": [
            "Anesthesia management for surgery",
            "Pain management",
            "Epidural injections",
            "Spinal anesthesia",
            "General anesthesia",
            "Local anesthesia",
            "Regional anesthesia",
            "Conscious sedation",
            "Intubation",
            "Ventilation management",
            "Intravenous (IV) anesthesia",
            "Anesthetic complications",
            "Postoperative pain control",
            "Chronic pain management",
            "Neuropathic pain",
            "Postherpetic neuralgia",
            "Cancer pain",
            "Fibromyalgia",
            "Complex regional pain syndrome (CRPS)",
            "Palliative care"
        ],
        "Surgeon": [
            "Appendicitis",
            "Gallbladder disease",
            "Hernias",
            "Colorectal cancer",
            "Breast cancer",
            "Thyroid nodules",
            "Gastrointestinal bleeding",
            "Diverticulitis",
            "Gastroesophageal reflux disease (GERD)",
            "Pancreatitis",
            "Appendectomy",
            "Cholecystectomy",
            "Colectomy",
            "Mastectomy",
            "Hemorrhoidectomy",
            "Thyroidectomy",
            "Bariatric surgery",
            "Liver resection",
            "Lung resection",
            "Esophagectomy"
        ],"Physician Executive": [
            "Healthcare management and leadership",
            "Strategic planning",
            "Quality improvement initiatives",
            "Population health management",
            "Healthcare policy and advocacy",
            "Risk management",
            "Clinical governance",
            "Healthcare technology implementation",
            "Financial management in healthcare",
            "Physician engagement",
            "Patient safety",
            "Telehealth and digital health initiatives",
            "Physician burnout prevention",
            "Medical staff relations",
            "Healthcare innovation",
            "Value-based care initiatives",
            "Performance metrics and analytics",
            "Interprofessional collaboration",
            "Medical education and training",
            "Healthcare ethics and compliance"
        ],
        "Addiction Medicine Specialist": [
            "Substance use disorders",
            "Alcohol addiction",
            "Opioid addiction",
            "Cocaine addiction",
            "Methamphetamine addiction",
            "Prescription drug addiction",
            "Dual diagnosis (co-occurring mental health and substance use disorders)",
            "Behavioral addictions (gambling, sex, internet)",
            "Intervention strategies",
            "Medication-assisted treatment (MAT)",
            "Detoxification",
            "Relapse prevention",
            "Counseling and therapy for addiction",
            "12-step programs",
            "Harm reduction",
            "Recovery management",
            "Family interventions",
            "Adolescent substance use",
            "Peer support programs",
            "Community-based addiction services"
        ],
        "Adolescent Medicine Specialist": [
            "Teenagers' general health and well-being",
            "Adolescent mental health",
            "Eating disorders (anorexia, bulimia)",
            "Acne and skin conditions",
            "Menstrual disorders",
            "Sexual and reproductive health",
            "Contraception counseling",
            "Substance use in adolescents",
            "Behavioral and emotional issues",
            "Sports injuries",
            "Adolescent nutrition",
            "Vaccination and immunization",
            "Teen pregnancy",
            "STI prevention and management",
            "Chronic illnesses in adolescents",
            "Puberty-related concerns",
            "Sleep disorders",
            "Teen parenting support",
            "School-related health issues",
            "Adolescent preventive care"
        ],
        "Allergist (Immunologist)": [
            "Allergic rhinitis (hay fever)",
            "Asthma",
            "Food allergies",
            "Insect sting allergies",
            "Drug allergies",
            "Eczema (atopic dermatitis)",
            "Contact dermatitis",
            "Urticaria (hives)",
            "Angioedema",
            "Anaphylaxis",
            "Allergic conjunctivitis",
            "Allergic bronchopulmonary aspergillosis",
            "Latex allergies",
            "Immunodeficiency disorders",
            "Autoimmune disorders",
            "Patch testing for allergies",
            "Desensitization (allergy shots)",
            "Intradermal skin testing",
            "Spirometry for lung function",
            "Blood tests for allergies"
        ],
        "Anatomic Pathologist": [
            "Surgical pathology",
            "Cancer diagnosis and staging",
            "Tissue biopsies",
            "Cytopathology",
            "Autopsy pathology",
            "Histopathology",
            "Fine needle aspiration (FNA) biopsy interpretation",
            "Immunohistochemistry",
            "Molecular pathology",
            "Frozen section analysis",
            "Gynecologic pathology",
            "Dermatopathology",
            "Neuropathology",
            "Hematopathology",
            "Breast pathology",
            "Gastrointestinal pathology",
            "Genitourinary pathology",
            "Respiratory pathology",
            "Endocrine pathology",
            "Musculoskeletal pathology"
        ],
        "Cardiac Electrophysiologist": [
            "Atrial fibrillation",
            "Atrial flutter",
            "Supraventricular tachycardia (SVT)",
            "Ventricular tachycardia",
            "Bradyarrhythmias",
            "Arrhythmogenic right ventricular dysplasia (ARVD)",
            "Wolff-Parkinson-White (WPW) syndrome",
            "Long QT syndrome",
            "Short QT syndrome",
            "Catecholaminergic polymorphic ventricular tachycardia (CPVT)",
            "Cardiac ablation procedures",
            "Pacemaker implantation",
            "Implantable cardioverter-defibrillator (ICD) implantation",
            "Cardiac resynchronization therapy (CRT)",
            "Electrophysiology studies",
            "Syncope (fainting) evaluation",
            "Holter and event monitoring",
            "Tilt table testing",
            "Inherited arrhythmia syndromes"
        ],
        "Cardiovascular Surgeon": [
            "Coronary artery bypass grafting (CABG)",
            "Valve replacement surgery",
            "Valve repair surgery",
            "Aneurysm repair",
            "Heart transplant surgery",
            "Ventricular assist device (VAD) implantation",
            "Aortic dissection repair",
            "Minimally invasive heart surgery",
            "Congenital heart defect repair",
            "Thoracic aortic surgery",
            "Arrhythmia surgery",
            "Peripheral artery bypass surgery",
            "Carotid artery surgery",
            "Endovascular aortic aneurysm repair (EVAR)",
            "Lung cancer surgery",
            "Esophageal cancer surgery",
            "Chest wall tumor resection",
            "Diaphragm repair",
            "Heart and lung transplantation",
            "Heart and lung transplant rejection management"
        ],
        "Clinical Laboratory Immunologist": [
            "Immunodeficiency disorders",
            "Autoimmune diseases",
            "Allergy testing",
            "Immunotherapy monitoring",
            "HIV/AIDS testing and monitoring",
            "Flow cytometry",
            "Serological testing",
            "Immunoglobulin disorders",
            "Complement system disorders",
            "Transplant immunology",
            "Rheumatologic disorders",
            "Inflammatory bowel disease (IBD) monitoring",
            "Cytokine testing",
            "T-cell and B-cell function testing",
            "Primary immunodeficiency disorders",
            "Secondary immunodeficiency disorders",
            "Hematologic malignancies",
            "Antibody deficiency syndromes",
            "Vaccine responsiveness testing"
        ],
        "Colon and Rectal Surgeon": [
            "Colorectal cancer",
            "Colonic polyps",
            "Inflammatory bowel disease (Crohn's disease, ulcerative colitis)",
            "Diverticulitis",
            "Rectal prolapse",
            "Anorectal abscess and fistula",
            "Anal fissures",
            "Hemorrhoids",
            "Colonoscopy",
            "Flexible sigmoidoscopy",
            "Colon and rectal surgery",
            "Laparoscopic colectomy",
            "Robotic-assisted colorectal surgery",
            "Bowel obstruction",
            "Anorectal cancer",
            "Incontinence",
            "Crohn's disease surgery",
            "Ulcerative colitis surgery",
            "Colostomy and ileostomy care",
            "Pelvic floor disorders"
        ],"Critical Care Medicine Specialist": [
            "Sepsis",
            "Respiratory failure",
            "Shock",
            "Multiple organ failure",
            "Acute respiratory distress syndrome (ARDS)",
            "Sepsis-induced coagulopathy",
            "Cardiogenic shock",
            "Septic shock",
            "Hypovolemic shock",
            "Neurogenic shock",
            "Trauma-related critical care",
            "Postoperative critical care",
            "Acute kidney injury",
            "Hepatic failure",
            "Gastrointestinal bleeding",
            "Pancreatitis",
            "Severe burns",
            "Intracranial hypertension",
            "Cerebral edema",
            "Acute coronary syndromes"
        ],
        "Cytopathologist": [
            "Fine needle aspiration (FNA) cytology",
            "Pap smears",
            "Cervical dysplasia",
            "Cervical cancer",
            "Endometrial hyperplasia",
            "Ovarian cancer",
            "Breast cytology",
            "Breast cancer",
            "Thyroid nodules",
            "Thyroid cancer",
            "Salivary gland tumors",
            "Lung cancer",
            "Gastrointestinal cytology",
            "Pancreatic cancer",
            "Liver cytology",
            "Kidney cytology",
            "Urinary tract cytology",
            "Prostate cytology",
            "Testicular cancer",
            "Soft tissue tumors"
        ],
        "Dermatopathologist": [
            "Skin cancer (melanoma, basal cell carcinoma, squamous cell carcinoma)",
            "Melanocytic nevi",
            "Dermatitis",
            "Psoriasis",
            "Lichen planus",
            "Cutaneous lymphoma",
            "Mycosis fungoides",
            "Lupus erythematosus",
            "Vasculitis",
            "Bullous diseases",
            "Granuloma annulare",
            "Infectious skin diseases",
            "Eczema (atopic dermatitis)",
            "Pityriasis rosea",
            "Connective tissue diseases affecting the skin",
            "Genodermatoses",
            "Hair disorders",
            "Nail disorders",
            "Molluscum contagiosum",
            "Cutaneous manifestations of systemic diseases"
        ],
        "Developmental Pediatrician": [
            "Autism spectrum disorder",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Intellectual disability",
            "Speech and language delays",
            "Learning disabilities",
            "Motor skill delays",
            "Cerebral palsy",
            "Down syndrome",
            "Genetic disorders affecting development",
            "Fetal alcohol syndrome",
            "Developmental delay",
            "Behavioral disorders",
            "Emotional disorders",
            "Feeding difficulties",
            "Sensory processing disorders",
            "Social communication disorders",
            "Global developmental delay",
            "Prader-Willi syndrome",
            "Rett syndrome",
            "Tourette syndrome"
        ],
        "Emergency Medicine Specialist": [
            "Myocardial infarction (heart attack)",
            "Stroke",
            "Traumatic injuries",
            "Severe infections",
            "Respiratory distress",
            "Acute abdominal pain",
            "Seizures and convulsions",
            "Anaphylaxis",
            "Hypovolemic shock",
            "Cardiogenic shock",
            "Septic shock",
            "Respiratory failure",
            "Pneumothorax",
            "Acute kidney injury",
            "Gastrointestinal bleeding",
            "Severe burns",
            "Poisonings and overdoses",
            "Head injuries",
            "Fractures and dislocations",
            "Psychiatric emergencies"
        ],
        "Endocrinologist": [
            "Type 1 diabetes",
            "Type 2 diabetes",
            "Thyroid disorders (hypothyroidism, hyperthyroidism)",
            "Adrenal disorders (Cushing's syndrome, Addison's disease)",
            "Polycystic ovary syndrome (PCOS)",
            "Hormone disorders",
            "Osteoporosis",
            "Metabolic syndrome",
            "Pituitary disorders",
            "Growth hormone disorders",
            "Parathyroid disorders",
            "Calcium disorders",
            "Lipid disorders",
            "Menstrual disorders",
            "Hirsutism",
            "Infertility",
            "Pituitary tumors",
            "Thyroid cancer",
            "Endocrine hypertension",
            "Adrenal tumors"
        ],
        "Forensic Pathologist": [
            "Autopsy examinations",
            "Cause and manner of death determination",
            "Trauma-related deaths",
            "Homicide investigations",
            "Suicide investigations",
            "Accidental deaths",
            "Death from natural causes",
            "Identification of human remains",
            "Child abuse investigations",
            "Sexual assault examinations",
            "Toxicology analysis",
            "Postmortem imaging",
            "Forensic anthropology",
            "Forensic entomology",
            "Mass disaster identification",
            "Expert testimony in legal cases",
            "Documentation of injuries",
            "Analysis of gunshot wounds",
            "Death in custody investigations",
            "Forensic odontology"
        ],
        "Gastroenterologist": [
            "Gastroesophageal reflux disease (GERD)",
            "Peptic ulcers",
            "Inflammatory bowel disease (Crohn's disease, ulcerative colitis)",
            "Irritable bowel syndrome (IBS)",
            "Celiac disease",
            "Colorectal cancer",
            "Gallstones",
            "Liver cirrhosis",
            "Hepatitis (viral and autoimmune)",
            "Pancreatitis",
            "Gastrointestinal bleeding",
            "Gastrointestinal polyps",
            "Diverticulitis",
            "Barrett's esophagus",
            "Malabsorption disorders",
            "Helicobacter pylori infection",
            "Eosinophilic esophagitis",
            "Gastrointestinal motility disorders",
            "Biliary tract diseases"
        ],"Geriatric Psychiatrist": [
            "Dementia (Alzheimer's disease, vascular dementia)",
            "Depression in the elderly",
            "Anxiety disorders",
            "Late-life psychosis",
            "Bipolar disorder in older adults",
            "Memory loss",
            "Cognitive impairment",
            "Delirium",
            "Sleep disorders in the elderly",
            "Grief and bereavement issues",
            "Medication management in older adults",
            "Elder abuse and neglect",
            "Adjustment disorders",
            "Personality disorders in the elderly",
            "Psychosomatic disorders",
            "Neurocognitive disorders",
            "Substance use disorders in older adults",
            "Social isolation and loneliness",
            "End-of-life mental health issues",
            "Capacity and decision-making assessments"
        ],
        "Hand Surgeon": [
            "Carpal tunnel syndrome",
            "Dupuytren's contracture",
            "Trigger finger",
            "Tennis elbow (lateral epicondylitis)",
            "Golfer's elbow (medial epicondylitis)",
            "Hand and wrist fractures",
            "Arthritis of the hand and wrist",
            "Tendon injuries and repairs",
            "Nerve injuries",
            "Ganglion cysts",
            "De Quervain's tenosynovitis",
            "Hand infections",
            "Congenital hand anomalies",
            "Thumb injuries and arthritis",
            "Rheumatoid arthritis affecting the hand",
            "Hand tumors",
            "Replantation surgery",
            "Hand joint replacement",
            "Microsurgery for hand reconstruction",
            "Hand trauma and crush injuries"
        ],
        "Hematologist": [
            "Anemia",
            "Iron deficiency anemia",
            "Sickle cell disease",
            "Thalassemia",
            "Hemophilia",
            "Von Willebrand disease",
            "Deep vein thrombosis (DVT)",
            "Pulmonary embolism",
            "Hematologic malignancies (leukemia, lymphoma, myeloma)",
            "Myelodysplastic syndromes",
            "Bone marrow disorders",
            "Thrombocytopenia",
            "Polycythemia vera",
            "Essential thrombocythemia",
            "Hemolytic anemia",
            "Clotting disorders",
            "Platelet disorders",
            "Bleeding disorders",
            "Hemochromatosis",
            "Hemoglobinopathies"
        ],
        "Hepatologist": [
            "Hepatitis (viral and autoimmune)",
            "Cirrhosis",
            "Liver fibrosis",
            "Liver steatosis (fatty liver disease)",
            "Liver cancer",
            "Portal hypertension",
            "Ascites",
            "Liver transplantation",
            "Hepatic encephalopathy",
            "Alcoholic liver disease",
            "Non-alcoholic fatty liver disease (NAFLD)",
            "Primary biliary cholangitis",
            "Primary sclerosing cholangitis",
            "Hemochromatosis",
            "Wilson's disease",
            "Alpha-1 antitrypsin deficiency",
            "Liver biopsy interpretation",
            "Liver function tests",
            "Chronic liver diseases",
            "Hepatorenal syndrome"
        ],
        "Hospitalist": [
            "Pneumonia",
            "Sepsis",
            "Heart failure exacerbation",
            "COPD exacerbation",
            "Acute myocardial infarction",
            "Stroke",
            "Diabetic ketoacidosis (DKA)",
            "Deep vein thrombosis (DVT)",
            "Pulmonary embolism",
            "Gastrointestinal bleeding",
            "Acute kidney injury",
            "Cellulitis",
            "Community-acquired pneumonia",
            "Urinary tract infection (UTI)",
            "Cerebrovascular accident (CVA)",
            "Cirrhosis decompensation",
            "Hypertensive crisis",
            "Seizure disorders",
            "Syncope",
            "Delirium"
        ],
        "Hyperbaric Physician": [
            "Chronic non-healing wounds",
            "Diabetic foot ulcers",
            "Compromised skin grafts and flaps",
            "Radiation tissue damage",
            "Crush injuries",
            "Necrotizing soft tissue infections",
            "Gas gangrene",
            "Carbon monoxide poisoning",
            "Decompression sickness",
            "Air or gas embolism",
            "Arterial insufficiency ulcers",
            "Chronic osteomyelitis",
            "Clostridial myonecrosis (gas gangrene)",
            "Refractory osteoradionecrosis",
            "Sudden sensorineural hearing loss",
            "Central retinal artery occlusion",
            "Acute traumatic ischemias",
            "Problematic surgical wounds",
            "Wound healing in compromised patients",
            "Infections involving bone"
        ],
        "Infectious Disease Specialist": [
            "Bacterial infections",
            "Viral infections",
            "Fungal infections",
            "Parasitic infections",
            "Sepsis",
            "HIV/AIDS",
            "Tuberculosis",
            "Meningitis",
            "Pneumonia",
            "Infective endocarditis",
            "Skin and soft tissue infections",
            "Urinary tract infections (UTI)",
            "Bone and joint infections",
            "Gastrointestinal infections",
            "Tick-borne illnesses",
            "Vector-borne diseases",
            "Travel-related infections",
            "Respiratory tract infections",
            "Sexually transmitted infections (STI)",
            "Antimicrobial resistance"
        ],
        "Interventional Cardiologist": [
            "Coronary artery disease",
            "Myocardial infarction (heart attack)",
            "Angina",
            "Coronary artery stenosis",
            "Peripheral artery disease",
            "Cardiac catheterization",
            "Coronary angioplasty",
            "Coronary stent placement",
            "Balloon valvuloplasty",
            "Atherectomy",
            "Thrombectomy",
            "Closure of atrial septal defects (ASD)",
            "Closure of patent foramen ovale (PFO)",
            "Treatment of cardiac arrhythmias",
            "Percutaneous coronary intervention (PCI)",
            "Transcatheter aortic valve replacement (TAVR)",
            "Mitral valve repair",
            "Carotid artery stenting",
            "Peripheral vascular interventions",
            "Coronary artery bypass graft (CABG) planning"
        ],
        "Medical Examiner": [
            "Cause and manner of death determination",
            "Autopsy examinations",
            "Forensic toxicology",
            "Postmortem imaging",
            "Identification of human remains",
            "Analysis of injuries and trauma",
            "Documentation of postmortem findings",
            "Forensic anthropology",
            "Forensic entomology",
            "Expert testimony in legal cases",
            "Death investigations",
            "Child abuse investigations",
            "Homicide investigations",
            "Suicide investigations",
            "Accidental deaths",
            "Natural deaths",
            "Mass disaster identification",
            "Forensic odontology",
            "Death in custody investigations",
            "Forensic pathology consultations"
        ],"Medical Geneticist": [
            "Genetic disorders",
            "Chromosomal abnormalities",
            "Inborn errors of metabolism",
            "Hereditary cancer syndromes",
            "Connective tissue disorders",
            "Neurogenetic disorders",
            "Genetic counseling",
            "Carrier screening",
            "Prenatal genetic testing",
            "Pediatric genetic disorders",
            "Adult-onset genetic conditions",
            "Genetic testing for rare diseases",
            "Pharmacogenetics",
            "Genomic medicine",
            "Huntington's disease",
            "Cystic fibrosis",
            "Down syndrome",
            "Muscular dystrophies",
            "Fragile X syndrome",
            "Thalassemia"
        ],
        "Neonatologist": [
            "Preterm birth complications",
            "Neonatal respiratory distress syndrome",
            "Neonatal sepsis",
            "Neonatal jaundice",
            "Neonatal hypoglycemia",
            "Congenital anomalies",
            "Neonatal abstinence syndrome",
            "Perinatal asphyxia",
            "Intrauterine growth restriction (IUGR)",
            "Neonatal cardiac disorders",
            "Neonatal neurologic disorders",
            "Neonatal surgery complications",
            "Neonatal metabolic disorders",
            "Neonatal hematology disorders",
            "Neonatal infectious diseases",
            "Neonatal nutrition issues",
            "Neonatal endocrine disorders",
            "Neonatal renal disorders",
            "Neonatal gastrointestinal disorders",
            "Neonatal dermatologic conditions"
        ],
        "Nephrologist": [
            "Chronic kidney disease",
            "Acute kidney injury",
            "Hypertension-related kidney disease",
            "Glomerulonephritis",
            "Polycystic kidney disease",
            "Kidney stones",
            "Nephrotic syndrome",
            "Diabetic nephropathy",
            "Renal artery stenosis",
            "Interstitial nephritis",
            "Renal cysts and tumors",
            "Hematuria",
            "Proteinuria",
            "Electrolyte imbalances",
            "Renal tubular acidosis",
            "Vasculitis affecting the kidneys",
            "Acute glomerulonephritis",
            "Hemolytic uremic syndrome",
            "Post-infectious glomerulonephritis",
            "Renal artery embolism"
        ],
        "Neurodevelopmental Pediatrician": [
            "Autism spectrum disorder",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Intellectual disability",
            "Speech and language delays",
            "Learning disabilities",
            "Motor skill delays",
            "Cerebral palsy",
            "Down syndrome",
            "Genetic syndromes affecting development",
            "Fetal alcohol syndrome",
            "Developmental delay",
            "Behavioral disorders",
            "Emotional disorders",
            "Feeding difficulties",
            "Sensory processing disorders",
            "Social communication disorders",
            "Global developmental delay",
            "Prader-Willi syndrome",
            "Rett syndrome",
            "Tourette syndrome"
        ],
        "Neurological Surgeon": [
            "Brain tumors",
            "Spinal cord tumors",
            "Cerebrovascular disorders",
            "Stroke",
            "Aneurysms",
            "Arteriovenous malformations (AVMs)",
            "Epilepsy surgery",
            "Movement disorders (Parkinson's disease, essential tremor)",
            "Peripheral nerve surgery",
            "Cranial nerve disorders",
            "Hydrocephalus",
            "Spinal disorders",
            "Spinal fusion surgery",
            "Disc herniation",
            "Scoliosis surgery",
            "Chiari malformation",
            "Neurotrauma (head and spinal cord injuries)",
            "Pituitary tumors",
            "Trigeminal neuralgia",
            "Moyamoya disease"
        ],
        "Neuromusculoskeletal Medicine Doctor": [
            "Musculoskeletal pain syndromes",
            "Osteoarthritis",
            "Rheumatoid arthritis",
            "Fibromyalgia",
            "Myofascial pain syndrome",
            "Bursitis and tendonitis",
            "Spinal disorders",
            "Back pain",
            "Neck pain",
            "Peripheral nerve disorders",
            "Peripheral neuropathy",
            "Complex regional pain syndrome (CRPS)",
            "Muscle disorders",
            "Movement disorders",
            "Sports-related injuries",
            "Work-related musculoskeletal disorders",
            "Joint hypermobility",
            "Soft tissue injuries",
            "Osteoporosis",
            "Postural and biomechanical disorders"
        ],
        "Neuropathologist": [
            "Alzheimer's disease",
            "Parkinson's disease",
            "Amyotrophic lateral sclerosis (ALS)",
            "Huntington's disease",
            "Prion diseases",
            "Frontotemporal dementia",
            "Vascular dementia",
            "Lewy body dementia",
            "Multiple sclerosis",
            "Cerebrovascular disease",
            "Brain tumors",
            "Peripheral nerve disorders",
            "Neuromuscular disorders",
            "Neurodegenerative disorders",
            "Traumatic brain injury",
            "Inflammatory disorders of the nervous system",
            "Hereditary neuropathies",
            "Infectious diseases affecting the nervous system",
            "Metabolic disorders affecting the nervous system"
        ],
        "Neuroradiologist": [
            "Brain and spinal cord tumors",
            "Cerebrovascular disorders",
            "Stroke",
            "Aneurysms",
            "Arteriovenous malformations (AVMs)",
            "Traumatic brain injury",
            "Multiple sclerosis",
            "Neurodegenerative disorders",
            "Epilepsy imaging",
            "Head and neck tumors",
            "Peripheral nerve disorders",
            "Spinal disorders",
            "Spinal cord injury",
            "Intracranial hemorrhage",
            "Cranial nerve disorders",
            "Pituitary gland disorders",
            "Neuroinfectious diseases",
            "Cerebral ischemia",
            "Cerebral atrophy"
        ],
        "Nuclear Medicine Specialist": [
            "Cancer staging and detection",
            "Bone scans",
            "Thyroid disorders",
            "Cardiac imaging",
            "Myocardial perfusion imaging",
            "Positron emission tomography (PET) scans",
            "Sentinel lymph node mapping",
            "Gastrointestinal bleeding studies",
            "Pulmonary embolism imaging",
            "Renal function studies",
            "Thallium scans",
            "Octreotide scans",
            "Parathyroid imaging",
            "Liver and spleen imaging",
            "Gallium scans",
            "Bone mineral density studies",
            "White blood cell scans",
            "Infection imaging",
            "Brain perfusion imaging",
            "Neuroendocrine tumor imaging"
        ],
        "Obstetrician": [
            "Pregnancy care and management",
            "Prenatal screenings and ultrasounds",
            "High-risk pregnancies",
            "Labor and delivery care",
            "Cesarean sections",
            "Vaginal births after cesarean (VBAC)",
            "Gestational diabetes management",
            "Preeclampsia and hypertension in pregnancy",
            "Multiple pregnancies (twins, triplets)",
            "Fetal growth disorders",
            "Maternal infections during pregnancy",
            "Placenta previa",
            "Preterm labor",
            "Fetal anomalies and genetic disorders",
            "Obstetric emergencies",
            "Postpartum care",
            "Family planning and contraception",
            "Menstrual disorders",
            "Polycystic ovary syndrome (PCOS)",
            "Endometriosis"
        ],"Occupational Medicine Specialist": [
            "Work-related musculoskeletal disorders",
            "Occupational injuries (falls, strains, fractures)",
            "Occupational dermatitis",
            "Noise-induced hearing loss",
            "Repetitive strain injuries (RSI)",
            "Occupational lung diseases",
            "Work-related stress and mental health issues",
            "Chemical exposure and toxicity",
            "Ergonomic-related issues",
            "Occupational infectious diseases",
            "Occupational eye injuries",
            "Cumulative trauma disorders",
            "Occupational asthma",
            "Heat-related illnesses",
            "Cold-related illnesses",
            "Biological hazards in the workplace",
            "Occupational cancers",
            "Occupational reproductive hazards",
            "Occupational lead exposure",
            "Occupational radiation exposure"
        ],
        "Orthopedic Surgeon": [
            "Fractures and dislocations",
            "Osteoarthritis",
            "Rheumatoid arthritis",
            "Meniscal tears",
            "ACL and PCL injuries",
            "Rotator cuff tears",
            "Frozen shoulder",
            "Carpal tunnel syndrome",
            "Tennis and golfer's elbow",
            "Hip labral tear",
            "Spinal disorders (herniated discs, spinal stenosis)",
            "Scoliosis",
            "Degenerative disc disease",
            "Osteoporotic fractures",
            "Bursitis and tendonitis",
            "Plantar fasciitis",
            "Achilles tendon injuries",
            "Bone tumors",
            "Joint infections",
            "Orthopedic trauma"
        ],
        "Otolaryngologist (Head and Neck Surgeon)": [
            "Sinusitis and nasal polyps",
            "Allergic rhinitis",
            "Ear infections",
            "Hearing loss",
            "Tinnitus",
            "Dizziness and vertigo",
            "Throat infections",
            "Tonsillitis",
            "Voice disorders",
            "Swallowing disorders",
            "Sleep apnea",
            "Snoring",
            "Thyroid nodules and disorders",
            "Salivary gland disorders",
            "Head and neck cancers",
            "Facial trauma",
            "Temporal bone disorders",
            "Facial paralysis",
            "Nasal and sinus tumors",
            "Laryngeal cancer"
        ],
        "Pain Management Specialist": [
            "Chronic pain syndromes",
            "Back pain",
            "Neck pain",
            "Joint pain",
            "Neuropathic pain",
            "Fibromyalgia",
            "Complex regional pain syndrome (CRPS)",
            "Migraines and headaches",
            "Arthritis pain",
            "Post-surgical pain",
            "Cancer-related pain",
            "Pain from nerve injuries",
            "Myofascial pain",
            "Pelvic pain",
            "Pain due to musculoskeletal injuries",
            "Pain in autoimmune disorders",
            "Phantom limb pain",
            "Temporomandibular joint (TMJ) pain",
            "Pain in neurological disorders",
            "Visceral pain"
        ],
        "Palliative Medicine Specialist": [
            "Advanced cancer pain management",
            "End-of-life care",
            "Symptom control in serious illnesses",
            "Palliative chemotherapy",
            "Palliative radiation therapy",
            "Management of treatment side effects",
            "Palliative care for heart failure",
            "Palliative care for chronic respiratory diseases",
            "Hospice care",
            "Advance care planning",
            "Psychosocial support for patients and families",
            "Spiritual care",
            "Management of fatigue and weakness",
            "Nausea and vomiting control",
            "Dyspnea (shortness of breath) management",
            "Loss of appetite and weight loss",
            "Delirium and confusion in serious illness",
            "Palliative care for neurodegenerative diseases",
            "Palliative care for end-stage renal disease",
            "Palliative care for liver failure"
        ],
        "Pathologist": [
            "Histopathological examination of tissues",
            "Cytological examination of cells",
            "Tumor grading and staging",
            "Cancer diagnosis",
            "Infectious disease pathology",
            "Autopsy and post-mortem examinations",
            "Immunohistochemistry",
            "Molecular pathology",
            "Hematopathology",
            "Clinical pathology",
            "Cytopathology",
            "Renal pathology",
            "Gastrointestinal pathology",
            "Gynecological pathology",
            "Breast pathology",
            "Neuropathology",
            "Dermatopathology",
            "Pulmonary pathology",
            "Musculoskeletal pathology",
            "Forensic pathology"
        ],
        "Pediatric Allergist": [
            "Asthma in children",
            "Allergic rhinitis (hay fever)",
            "Food allergies",
            "Eczema (atopic dermatitis)",
            "Contact dermatitis",
            "Insect sting allergies",
            "Drug allergies",
            "Anaphylaxis",
            "Allergic conjunctivitis",
            "Latex allergy",
            "Hay fever",
            "Hives (urticaria)",
            "Angioedema",
            "Patch testing for allergies",
            "Immune deficiency disorders in children",
            "Allergy testing and diagnosis",
            "Oral food challenges",
            "Desensitization (allergy shots)",
            "Environmental allergens",
            "Adverse reactions to vaccines"
        ],
        "Pediatric Cardiologist": [
            "Congenital heart defects",
            "Pediatric arrhythmias",
            "Kawasaki disease",
            "Pediatric heart murmurs",
            "Pediatric chest pain",
            "Heart failure in children",
            "Acquired heart diseases in children",
            "Rheumatic heart disease in children",
            "Pediatric high blood pressure",
            "Infectious heart diseases in children",
            "Cardiomyopathies in children",
            "Syncope (fainting) in children",
            "Cyanotic and acyanotic heart conditions",
            "Pediatric heart catheterization",
            "Pediatric cardiac surgery",
            "Sports cardiology in children",
            "Cardiovascular genetics in pediatrics",
            "Pediatric cardiac imaging",
            "Pediatric heart transplant",
            "Fetal cardiology"
        ],"Pediatric Endocrinologist": [
            "Type 1 diabetes",
            "Type 2 diabetes",
            "Congenital adrenal hyperplasia",
            "Growth disorders",
            "Puberty disorders",
            "Thyroid disorders",
            "Adrenal disorders",
            "Pituitary disorders",
            "Hypoglycemia",
            "Obesity-related endocrine issues",
            "Calcium and bone metabolism disorders",
            "Turner syndrome",
            "Klinefelter syndrome",
            "Polycystic ovary syndrome (PCOS) in adolescents",
            "Ambiguous genitalia and intersex conditions",
            "Neonatal hypoglycemia",
            "Diabetes insipidus",
            "Metabolic disorders",
            "Precocious puberty",
            "Delayed puberty"
        ],
        "Pediatric Gastroenterologist": [
            "Gastroesophageal reflux disease (GERD)",
            "Inflammatory bowel disease (Crohn's disease, ulcerative colitis)",
            "Celiac disease",
            "Food allergies and intolerances",
            "Chronic abdominal pain",
            "Constipation",
            "Diarrheal disorders",
            "Liver disorders",
            "Pancreatic disorders",
            "Gastrointestinal bleeding",
            "Malabsorption disorders",
            "Gastrointestinal infections",
            "Eosinophilic esophagitis",
            "Peptic ulcer disease",
            "Gallbladder and biliary tract disorders",
            "Hirschsprung's disease",
            "Short bowel syndrome",
            "Gastrointestinal motility disorders",
            "Appendicitis",
            "Gastrointestinal polyps"
        ],
        "Pediatric Hematologist": [
            "Anemia",
            "Sickle cell disease",
            "Thalassemia",
            "Hemophilia",
            "Von Willebrand disease",
            "Platelet disorders",
            "Leukemia",
            "Lymphoma",
            "Myelodysplastic syndromes",
            "Bone marrow failure syndromes",
            "Hemoglobinopathies",
            "White blood cell disorders",
            "Red blood cell disorders",
            "Coagulation disorders",
            "Hemolytic anemias",
            "Bleeding disorders",
            "Clotting disorders",
            "Neutropenia",
            "Thrombocytopenia",
            "Hematologic malignancies"
        ],
        "Pediatric Infectious Disease Specialist": [
            "Respiratory infections",
            "Gastrointestinal infections",
            "Urinary tract infections",
            "Skin and soft tissue infections",
            "Viral infections",
            "Bacterial infections",
            "Fungal infections",
            "Parasitic infections",
            "Meningitis",
            "Encephalitis",
            "Bone and joint infections",
            "Sepsis",
            "Immunization-related issues",
            "Febrile illnesses",
            "Tuberculosis in children",
            "HIV/AIDS in children",
            "Congenital infections",
            "Tick-borne infections",
            "Vaccine-preventable diseases",
            "Healthcare-associated infections in children"
        ],
        "Pediatric Nephrologist": [
            "Congenital kidney disorders",
            "Acute kidney injury in children",
            "Chronic kidney disease in children",
            "Glomerulonephritis",
            "Nephrotic syndrome",
            "Hematuria and proteinuria",
            "Urinary tract infections in children",
            "Renal cystic diseases",
            "Hydronephrosis",
            "Renal tubular disorders",
            "Vesicoureteral reflux",
            "Pediatric hypertension",
            "Polycystic kidney disease in children",
            "Renal stones in children",
            "Genetic kidney disorders",
            "Renal transplantation in children",
            "Pediatric dialysis",
            "Fluid and electrolyte disorders in children",
            "Acid-base disorders in children",
            "Renal manifestations of systemic diseases in children"
        ],
        "Pediatric Pulmonologist": [
            "Asthma in children",
            "Cystic fibrosis",
            "Bronchiolitis",
            "Pneumonia",
            "Chronic cough in children",
            "Wheezing disorders",
            "Respiratory distress syndrome (RDS) in newborns",
            "Sleep-disordered breathing in children",
            "Interstitial lung disease in children",
            "Congenital lung abnormalities",
            "Pulmonary vascular disorders in children",
            "Bronchopulmonary dysplasia (BPD)",
            "Primary ciliary dyskinesia",
            "Pulmonary infections in children",
            "Foreign body aspiration",
            "Allergic bronchopulmonary aspergillosis (ABPA)",
            "Sarcoidosis in children",
            "Neuromuscular respiratory disorders in children",
            "Pulmonary function testing in children",
            "Lung transplantation in children"
        ],
        "Pediatric Rheumatologist": [
            "Juvenile idiopathic arthritis",
            "Systemic lupus erythematosus (SLE) in children",
            "Juvenile dermatomyositis",
            "Kawasaki disease",
            "Henoch-Schönlein purpura",
            "Vasculitis in children",
            "Autoinflammatory syndromes in children",
            "Autoimmune disorders in children",
            "Pediatric scleroderma",
            "Juvenile ankylosing spondylitis",
            "Juvenile psoriatic arthritis",
            "Mixed connective tissue disease in children",
            "Periodic fever syndromes",
            "Bone and joint infections in children",
            "Reactive arthritis in children",
            "Pediatric fibromyalgia",
            "Pediatric osteoporosis",
            "Spondyloarthropathies in children",
            "Chronic nonbacterial osteomyelitis (CNO)",
            "Growth plate disorders in children"
        ],
        "Pediatric Surgeon": [
            "Congenital anomalies",
            "Pediatric tumors and cancers",
            "Gastrointestinal surgery in children",
            "Pediatric trauma surgery",
            "Thoracic surgery in children",
            "Abdominal wall defects in children",
            "Esophageal disorders in children",
            "Anorectal malformations",
            "Hernias in children",
            "Urologic surgery in children",
            "Neonatal surgery",
            "Laparoscopic and minimally invasive surgery in children",
            "Vascular anomalies in children",
            "Pediatric burn surgery",
            "Pediatric surgical oncology",
            "Head and neck surgery in children",
            "Pectus excavatum and carinatum",
            "Pediatric solid organ transplantation",
            "Fetal surgery",
            "Pediatric plastic and reconstructive surgery"
        ],
        "Pediatric Urologist": [
            "Hydronephrosis in children",
            "Vesicoureteral reflux",
            "Urinary tract infections in children",
            "Undescended testicles (cryptorchidism)",
            "Hypospadias",
            "Bladder exstrophy",
            "Neurogenic bladder in children",
            "Pediatric kidney stones",
            "Genitourinary tumors in children",
            "Pediatric genital abnormalities",
            "Pediatric urologic trauma",
            "Ureteropelvic junction (UPJ) obstruction",
            "Posterior urethral valves",
            "Wilms tumor",
            "Adrenal disorders in children",
            "Prune belly syndrome",
            "Renal duplication anomalies",
            "Ambiguous genitalia",
            "Pediatric urinary incontinence",
            "Pediatric renal transplantation"
        ],
        "Perinatologist": [
            "High-risk pregnancies",
            "Gestational diabetes",
            "Preeclampsia and eclampsia",
            "Multiple pregnancies (twins, triplets)",
            "Preterm labor and birth",
            "Fetal growth disorders",
            "Congenital anomalies detected in utero",
            "Rh incompatibility",
            "Fetal anemia",
            "Polyhydramnios and oligohydramnios",
            "Amniotic fluid disorders",
            "Preconception counseling",
            "Preterm premature rupture of membranes (PPROM)",
            "Intrauterine growth restriction (IUGR)",
            "Placental disorders",
            "Umbilical cord abnormalities",
            "Fetal arrhythmias",
            "Fetal surgery consultations",
            "Fetal echocardiography",
            "Maternal-fetal medicine consultations"
        ],"Physical Medicine and Rehabilitation Specialist": [
            "Muscle strains and sprains",
            "Joint injuries",
            "Back pain",
            "Neck pain",
            "Spinal cord injuries",
            "Stroke rehabilitation",
            "Amputations",
            "Traumatic brain injuries",
            "Neurological disorders",
            "Arthritis",
            "Sports injuries",
            "Work-related injuries",
            "Orthopedic injuries",
            "Repetitive strain injuries",
            "Balance disorders",
            "Gait abnormalities",
            "Cerebral palsy",
            "Multiple sclerosis",
            "Peripheral neuropathy",
            "Chronic pain syndromes"
        ],
        "Plastic Surgeon": [
            "Cosmetic surgery",
            "Breast augmentation",
            "Breast reduction",
            "Facelift",
            "Rhinoplasty",
            "Liposuction",
            "Tummy tuck",
            "Eyelid surgery",
            "Botox and fillers",
            "Body contouring",
            "Hair transplantation",
            "Scar revision",
            "Burn reconstruction",
            "Hand surgery",
            "Congenital deformities",
            "Gender-affirming surgery",
            "Microsurgery",
            "Cleft lip and palate repair",
            "Skin cancer reconstruction",
            "Traumatic injury reconstruction"
        ],
        "Preventive Medicine Specialist": [
            "Immunizations",
            "Routine health check-ups",
            "Cancer screenings",
            "Chronic disease prevention",
            "Healthy lifestyle counseling",
            "Diet and nutrition counseling",
            "Exercise prescriptions",
            "Smoking cessation",
            "Weight management",
            "Blood pressure management",
            "Cholesterol management",
            "Preventive cardiology",
            "Diabetes prevention",
            "Osteoporosis prevention",
            "Mental health promotion",
            "Stress management",
            "Infectious disease prevention",
            "Environmental health assessments",
            "Genetic counseling",
            "Occupational health assessments"
        ],
        "Psychiatrist (Child and Adolescent)": [
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Autism spectrum disorders",
            "Oppositional defiant disorder (ODD)",
            "Conduct disorder",
            "Anxiety disorders",
            "Depression",
            "Bipolar disorder",
            "Eating disorders",
            "Obsessive-compulsive disorder (OCD)",
            "Post-traumatic stress disorder (PTSD)",
            "Schizophrenia",
            "Mood disorders",
            "Self-harm and suicidal behavior",
            "School-related issues",
            "Learning disabilities",
            "Developmental disorders",
            "Substance abuse",
            "Family and relationship issues",
            "Grief and loss",
            "Psychosomatic disorders"
        ],
        "Pulmonologist": [
            "Asthma",
            "Chronic obstructive pulmonary disease (COPD)",
            "Interstitial lung disease",
            "Pneumonia",
            "Lung cancer",
            "Bronchitis",
            "Emphysema",
            "Pulmonary fibrosis",
            "Sleep apnea",
            "Cystic fibrosis",
            "Pulmonary hypertension",
            "Tuberculosis",
            "Occupational lung diseases",
            "Allergic lung diseases",
            "Respiratory infections",
            "Sarcoidosis",
            "Pulmonary embolism",
            "Lung nodules",
            "Pleural effusion",
            "Hemoptysis"
        ],
        "Radiation Oncologist": [
            "Breast cancer",
            "Prostate cancer",
            "Lung cancer",
            "Colorectal cancer",
            "Head and neck cancers",
            "Brain tumors",
            "Liver cancer",
            "Pancreatic cancer",
            "Gynecological cancers",
            "Bladder cancer",
            "Kidney cancer",
            "Thyroid cancer",
            "Skin cancers",
            "Lymphomas",
            "Leukemias",
            "Bone cancers",
            "Soft tissue sarcomas",
            "Gastrointestinal cancers",
            "Genitourinary cancers",
            "Hematologic malignancies"
        ],
        "Reproductive Endocrinologist": [
            "Infertility",
            "Polycystic ovary syndrome (PCOS)",
            "Endometriosis",
            "Male factor infertility",
            "Ovulatory disorders",
            "Recurrent pregnancy loss",
            "In vitro fertilization (IVF)",
            "Egg freezing",
            "Sperm and egg donation",
            "Surrogacy",
            "Uterine abnormalities",
            "Premature ovarian insufficiency",
            "Hormonal imbalances",
            "Fertility preservation",
            "Gestational carrier",
            "Assisted reproductive technologies (ART)",
            "Ovarian cysts",
            "Pelvic inflammatory disease (PID)",
            "Menstrual disorders",
            "Reproductive cancers"
        ],
        "Rheumatologist": [
            "Rheumatoid arthritis",
            "Osteoarthritis",
            "Systemic lupus erythematosus (SLE)",
            "Sjögren's syndrome",
            "Ankylosing spondylitis",
            "Psoriatic arthritis",
            "Gout",
            "Vasculitis",
            "Scleroderma",
            "Myositis",
            "Fibromyalgia",
            "Osteoporosis",
            "Antiphospholipid syndrome",
            "Juvenile idiopathic arthritis",
            "Inflammatory myopathies",
            "Behçet's disease",
            "Lyme disease",
            "Mixed connective tissue disease",
            "Polymyalgia rheumatica",
            "Temporal arteritis (Giant cell arteritis)"
        ],
        "Sleep Disorders Specialist": [
            "Insomnia",
            "Sleep apnea",
            "Narcolepsy",
            "Restless legs syndrome",
            "Circadian rhythm disorders",
            "Parasomnias",
            "Nightmares",
            "Night terrors",
            "Sleepwalking",
            "Bruxism (teeth grinding)",
            "Shift work sleep disorder",
            "Insufficient sleep syndrome",
            "Jet lag",
            "Obstructive sleep apnea",
            "Central sleep apnea",
            "Complex sleep apnea syndrome",
            "Sleep-related eating disorder",
            "Sleep-related groaning",
            "Sleep-related leg cramps",
            "Nocturnal enuresis (bedwetting)"
        ],
        "Spinal Cord Injury Specialist": [
            "Traumatic spinal cord injuries",
            "Non-traumatic spinal cord injuries",
            "Spinal cord compression",
            "Spinal cord tumors",
            "Spinal cord vascular malformations",
            "Degenerative disc disease",
            "Spinal stenosis",
            "Herniated disc",
            "Spinal fractures",
            "Spinal cord infections",
            "Transverse myelitis",
            "Cauda equina syndrome",
            "Spinal cord contusions",
            "Spinal cord ischemia",
            "Spinal cord demyelination disorders",
            "Spinal cord syringomyelia",
            "Spinal cord tethering",
            "Spinal cord trauma rehabilitation",
            "Neurogenic bladder and bowel",
            "Spinal cord stimulator implantation"
        ],"Sports Medicine Specialist": [
            "Muscle strains and sprains",
            "Joint injuries",
            "Sports-related fractures",
            "Tendonitis",
            "Concussions",
            "ACL injuries",
            "Meniscus tears",
            "Rotator cuff injuries",
            "Tennis elbow",
            "Shin splints",
            "Stress fractures",
            "Ankle sprains",
            "Cartilage injuries",
            "Groin injuries",
            "Runner's knee",
            "Hamstring injuries",
            "Dislocations",
            "Overuse injuries",
            "Scoliosis",
            "Sports performance optimization"
        ],
        "Surgical Pathologist": [
            "Cancer diagnosis",
            "Tumor grading",
            "Tumor staging",
            "Biopsy interpretation",
            "Lymph node analysis",
            "Fine needle aspiration (FNA) analysis",
            "Histopathology",
            "Cytopathology",
            "Immunohistochemistry",
            "Molecular pathology",
            "Frozen section analysis",
            "Surgical margin assessment",
            "Infectious disease pathology",
            "Gastrointestinal pathology",
            "Gynecologic pathology",
            "Breast pathology",
            "Pulmonary pathology",
            "Renal pathology",
            "Hepatic pathology",
            "Endocrine pathology"
        ],
        "Thoracic Surgeon": [
            "Lung cancer",
            "Esophageal cancer",
            "Mediastinal tumors",
            "Tracheal tumors",
            "Lung nodules",
            "Lung infections",
            "Pleural diseases",
            "Chest wall tumors",
            "Thymic tumors",
            "Gastroesophageal reflux disease (GERD)",
            "Hiatal hernia",
            "Achalasia",
            "Pulmonary embolism",
            "Pneumothorax",
            "Empyema",
            "Mesothelioma",
            "Interstitial lung disease",
            "Benign lung tumors",
            "Lung transplantation",
            "Video-assisted thoracic surgery (VATS)"
        ],
        "Transplant Hepatologist": [
            "Liver transplantation",
            "Liver cirrhosis",
            "Hepatitis B",
            "Hepatitis C",
            "Alcoholic liver disease",
            "Non-alcoholic fatty liver disease (NAFLD)",
            "Autoimmune liver diseases",
            "Liver tumors",
            "Hepatocellular carcinoma (HCC)",
            "Liver cysts",
            "Liver abscess",
            "Portal hypertension",
            "Liver failure",
            "Wilson's disease",
            "Hemochromatosis",
            "Primary biliary cirrhosis",
            "Primary sclerosing cholangitis",
            "Liver biopsy interpretation",
            "Acute liver injury",
            "Liver hemangiomas"
        ],
        "Trauma Surgeon": [
            "Traumatic injuries",
            "Blunt force trauma",
            "Penetrating injuries",
            "Motor vehicle accidents",
            "Gunshot wounds",
            "Stab wounds",
            "Head injuries",
            "Spinal cord injuries",
            "Fractures and dislocations",
            "Chest injuries",
            "Abdominal injuries",
            "Pelvic injuries",
            "Extremity injuries",
            "Soft tissue injuries",
            "Trauma resuscitation",
            "Hemorrhagic shock",
            "Compartment syndrome",
            "Emergency surgery",
            "Trauma critical care",
            "Post-traumatic stress disorder (PTSD)"
        ],
        "Urologist": [
            "Kidney stones",
            "Bladder stones",
            "Urinary tract infections (UTIs)",
            "Bladder infections",
            "Interstitial cystitis",
            "Bladder cancer",
            "Prostate cancer",
            "Kidney cancer",
            "Testicular cancer",
            "Bladder dysfunction",
            "Prostate disorders",
            "Erectile dysfunction",
            "Male infertility",
            "Female urology",
            "Pelvic organ prolapse",
            "Overactive bladder",
            "Neurogenic bladder",
            "Hematuria",
            "Incontinence",
            "Sexually transmitted infections (STIs)"
        ],
        "Vascular and Interventional Radiologist": [
            "Peripheral artery disease (PAD)",
            "Carotid artery disease",
            "Aortic aneurysms",
            "Peripheral arterial occlusive disease",
            "Deep vein thrombosis (DVT)",
            "Pulmonary embolism",
            "Varicose veins",
            "Renal artery stenosis",
            "Hemodialysis access management",
            "Venous insufficiency",
            "Arteriovenous malformations (AVMs)",
            "Peripheral vascular interventions",
            "Vascular trauma",
            "Inferior vena cava filters",
            "Vascular embolization",
            "Angioplasty and stenting",
            "Thrombolysis",
            "Endovascular aneurysm repair (EVAR)",
            "Uterine fibroid embolization"
        ],
        "Vascular Surgeon": [
            "Aortic aneurysm repair",
            "Carotid artery surgery",
            "Peripheral artery bypass surgery",
            "Peripheral artery endarterectomy",
            "Varicose vein surgery",
            "Dialysis access surgery",
            "Venous thrombectomy",
            "Vascular trauma surgery",
            "Thrombolytic therapy",
            "Arteriovenous fistula creation",
            "Atherectomy",
            "Angioplasty and stenting",
            "Peripheral artery balloon angioplasty",
            "Peripheral artery revascularization",
            "Deep vein thrombosis (DVT) surgery",
            "Lymphedema surgery",
            "Vascular malformation surgery",
            "Vascular graft surgery",
            "Vascular bypass surgery"
        ]
    }
        

        for specialist, diagnoses in medical_diagnosis.items():
            for diagnosis in diagnoses:
                Diagnosis.objects.get_or_create(
                    name=diagnosis,
                    recommended_specialist=specialist
                )

        self.stdout.write(self.style.SUCCESS('Successfully populated diagnoses table'))
