from django.core.management.base import BaseCommand
from accounts.models import PhysicalExaminationResponse  # Replace 'myapp' with your actual app name

class Command(BaseCommand):
    help = 'Populates the database with physical examination responses'

    def handle(self, *args, **kwargs):
        physical_exam_responses = [
    "Normal blood pressure within the healthy range.",
    "Pupils are equal, round, and reactive to light (PERRLA).",
    "Full range of motion in all joints, no swelling or tenderness.",
    "Normal bowel sounds in all quadrants.",
    "No signs of jaundice, sclerae are white.",
    "Skin is warm, dry, and without lesions or rashes.",
    "Cranial nerves intact, normal facial symmetry.",
    "No signs of edema in the extremities.",
    "Normal grip strength and muscle tone.",
    "No signs of clubbing or cyanosis in the fingers.",
    "Able to perform coordinated movements and balance.",
    "Normal reflexes: deep tendon and superficial.",
    "No signs of abdominal distention or masses.",
    "No signs of lymphadenopathy or enlarged lymph nodes.",
    "Able to perform heel-to-toe walking without difficulty.",
    "Normal gait and posture.",
    "No signs of respiratory distress.",
    "Normal range of motion in the neck, no stiffness or pain.",
    "Normal testicular exam, no masses or tenderness.",
    "Able to perform finger-to-nose and rapid alternating movements.",
    "Normal visual acuity and peripheral vision.",
    "No signs of spinal deformities or abnormalities.",
    "Normal findings on breast examination, no lumps or discharge.",
    "Able to hear whispered words at a normal distance.",
    "Normal range of motion in the shoulders and elbows.",
    "No signs of pitting edema in the lower extremities.",
    "Normal findings on pelvic examination.",
    "No signs of hemorrhoids or rectal masses.",
    "Able to stand on tiptoes and heels without difficulty.",
    "Normal findings on prostate examination.",
    "No signs of varicose veins or leg ulcers.",
    "Able to perform a full squat without pain or difficulty.",
    "Normal findings on eye examination, no abnormalities.",
    "No signs of tremors or involuntary movements.",
    "Able to perform a full sit-up without pain or difficulty.",
    "Normal findings on ear examination, no discharge or abnormalities.",
    "No signs of ecchymosis or petechiae.",
    "Able to perform a full range of motion in the wrists and fingers.",
    "Normal findings on dental examination, no cavities or gum disease.",
    "No signs of abdominal tenderness or guarding.",
    "Able to stand on one leg without losing balance.",
    "Normal findings on genitourinary examination.",
    "No signs of jugular venous distention.",
    "Able to perform a full range of motion in the hips and knees.",
    "Normal findings on skin assessment, no lesions or moles of concern.",
    "No signs of respiratory retractions in the chest.",
    "Able to hop on one foot without difficulty.",
    "Normal findings on rectal examination, no masses or blood.",
    "No signs of asymmetry or drooping in the face.",
    "Able to perform toe-tapping and heel-shin sliding without difficulty.",
    "Normal findings on musculoskeletal examination.",
    "No signs of orthostatic hypotension.",
    "Able to perform the Rhomberg test without imbalance.",
    "Normal findings on neurological examination.",
    "No signs of respiratory asymmetry or paradoxical breathing.",
    "Able to perform the finger-thumb opposition test without difficulty.",
    "Normal findings on vascular examination.",
    "No signs of abdominal bruits or pulsations.",
    "Able to perform a full range of motion in the ankles and feet.",
    "Normal findings on abdominal examination, no masses or organ enlargement.",
    "No signs of hyperreflexia or hyporeflexia.",
    "Able to perform the Romberg test without swaying.",
    "Normal findings on cardiac examination, no murmurs or irregularities.",
    "No signs of hepatomegaly or splenomegaly.",
    "Able to perform the Tandem walk without difficulty.",
    "Normal findings on respiratory examination.",
    "No signs of cyanosis or pallor.",
    "Able to perform the finger-to-nose test with precision.",
    "Normal findings on joint examination, no swelling or effusion.",
    "No signs of claudication or peripheral artery disease.",
    "Able to perform the Lachman test without signs of ligamentous instability.",
    "Normal findings on cranial nerve examination.",
    "No signs of muscle atrophy or weakness.",
    "Able to perform the Dix-Hallpike maneuver without signs of vertigo.",
    "Normal findings on abdominal percussion, no organ enlargement or fluid.",
    "No signs of skin discoloration or mottling.",
    "Able to perform the Straight Leg Raise test without pain.",
    "Normal findings on breast palpation, no masses or abnormalities.",
    "No signs of joint redness or warmth.",
    "Able to perform the Phalen test without signs of carpal tunnel syndrome.",
    "Normal findings on thyroid examination, no enlargement or nodules.",
    "No signs of abnormal pulsations or thrills.",
    "Able to perform the Adams Forward Bend test without signs of scoliosis.",
    "Normal findings on ankle-brachial index assessment.",
    "No signs of crepitus or grinding in the joints.",
    "Able to perform the Pronator Drift test without signs of weakness.",
    "Normal findings on abdominal auscultation, no bruits or vascular abnormalities.",
    "No signs of abnormal abdominal masses or tenderness.",
    "Able to perform the Babinski reflex test with normal response.",
    "Normal findings on peripheral pulse examination, no deficits or abnormalities.",
    "No signs of jugular venous distention or pulsations.",
    "Able to perform the Trendelenburg test without difficulty.",
    "Normal findings on abdominal palpation, no masses or tenderness.",
    "No signs of abdominal rigidity or guarding.",
    "Able to perform the Timed Up and Go test without difficulty.",
    "Normal findings on carotid artery examination, no bruits or abnormalities."
]
        negative_physical_exam_responses = [
    "Elevated heart rate and irregular rhythm, possible murmurs detected.",
    "Diminished breath sounds bilaterally, wheezing and crackles present.",
    "High blood pressure readings, above the healthy range.",
    "Unequal and non-reactive pupils, potential neurological issues.",
    "Limited range of motion in multiple joints, significant tenderness noted.",
    "Abnormal bowel sounds in one or more quadrants.",
    "Yellowing of the sclerae, indicative of jaundice.",
    "Cool and clammy skin with visible lesions and rashes.",
    "Difficulty performing coordinated movements and balance issues.",
    "Abnormal reflexes, both deep tendon and superficial.",
    "Visible abdominal distention and palpable masses.",
    "Difficulty with heel-to-toe walking and abnormal gait.",
    "Signs of respiratory distress, including labored breathing.",
    "Stiffness and pain reported in the neck during range of motion.",
    "Abnormalities found during testicular examination.",
    "Challenges with finger-to-nose and rapid alternating movements.",
    "Visual impairments and abnormalities in peripheral vision.",
    "Visible spinal deformities and abnormalities.",
    "Lumps and discharge detected during breast examination.",
    "Hearing difficulties and abnormal responses to whispered words.",
    "Limited range of motion in the shoulders and elbows with pain.",
    "Visible pitting edema in the lower extremities.",
    "Abnormal findings on pelvic examination.",
    "Presence of hemorrhoids and palpable rectal masses.",
    "Inability to stand on tiptoes and heels without difficulty.",
    "Abnormal findings on prostate examination.",
    "Visible signs of varicose veins and leg ulcers.",
    "Pain reported during a full squat.",
    "Abnormal findings on eye examination, including abnormalities.",
    "Visible tremors and involuntary movements.",
    "Pain reported during a full sit-up.",
    "Abnormal findings on ear examination, including discharge.",
    "Signs of ecchymosis and petechiae.",
    "Limited range of motion in the wrists and fingers with pain.",
    "Cavities and gum disease detected during dental examination.",
    "Abdominal tenderness and guarding reported.",
    "Difficulty standing on one leg without losing balance.",
    "Abnormal findings on genitourinary examination.",
    "Visible jugular venous distention.",
    "Limited range of motion in the hips and knees with pain.",
    "Lesions and moles of concern found during skin assessment.",
    "Visible respiratory retractions in the chest.",
    "Difficulty hopping on one foot.",
    "Abnormal findings on rectal examination, including masses and blood.",
    "Visible asymmetry or drooping in the face.",
    "Challenges with toe-tapping and heel-shin sliding.",
    "Abnormal findings on musculoskeletal examination.",
    "Signs of orthostatic hypotension.",
    "Imbalance detected during the Rhomberg test.",
    "Abnormal findings on neurological examination.",
    "Visible signs of respiratory asymmetry or paradoxical breathing.",
    "Difficulty with the finger-thumb opposition test.",
    "Abnormal findings on vascular examination.",
    "Audible abdominal bruits and pulsations.",
    "Limited range of motion in the ankles and feet with pain.",
    "Abnormal findings on abdominal examination, including masses and organ enlargement.",
    "Signs of hyperreflexia or hyporeflexia.",
    "Swaying detected during the Romberg test.",
    "Abnormal findings on cardiac examination, including murmurs and irregularities.",
    "Visible signs of hepatomegaly or splenomegaly.",
    "Difficulty with the Tandem walk.",
    "Abnormal findings on respiratory examination.",
    "Visible signs of cyanosis or pallor.",
    "Difficulty with the finger-to-nose test.",
    "Abnormal findings on joint examination, including swelling and effusion.",
    "Claudication reported and signs of peripheral artery disease.",
    "Signs of ligamentous instability during the Lachman test.",
    "Abnormal findings on cranial nerve examination.",
    "Signs of muscle atrophy and weakness.",
    "Signs of vertigo during the Dix-Hallpike maneuver.",
    "Abnormal findings on abdominal percussion, including organ enlargement or fluid.",
    "Visible signs of skin discoloration or mottling.",
    "Pain reported during the Straight Leg Raise test.",
    "Abnormal findings on breast palpation, including masses and abnormalities.",
    "Joint redness and warmth reported.",
    "Signs of carpal tunnel syndrome during the Phalen test.",
    "Abnormal findings on thyroid examination, including enlargement or nodules.",
    "Visible abnormal pulsations or thrills.",
    "Abnormal findings on the Adams Forward Bend test, including signs of scoliosis.",
    "Abnormal findings on ankle-brachial index assessment.",
    "Crepitus and grinding reported in the joints.",
    "Signs of weakness detected during the Pronator Drift test.",
    "Abnormal findings on abdominal auscultation, including bruits or vascular abnormalities.",
    "Signs of abdominal masses or tenderness reported.",
    "Imbalance detected during the Babinski reflex test.",
    "Abnormal findings on abdominal palpation, including masses or tenderness.",
    "Signs of abdominal rigidity or guarding reported.",
    "Challenges with the Timed Up and Go test.",
    "Abnormal findings on carotid artery examination, including bruits or abnormalities."
    ]
            

        for response in physical_exam_responses:
            PhysicalExaminationResponse.objects.get_or_create(
                response=response, response_type='positive'
            )

        for response in negative_physical_exam_responses:
            PhysicalExaminationResponse.objects.get_or_create(
                response=response, response_type='negative'
            )

        self.stdout.write(self.style.SUCCESS('Successfully populated physical examination responses table'))
