from django.core.management.base import BaseCommand
from accounts.models import Symptom  # Replace 'myapp' with your actual app name

class Command(BaseCommand):
    help = 'Populates the database with medical symptoms and their associated specialists'

    def handle(self, *args, **kwargs):
        medical_symptoms = {
        "Family Practice Physician": ["General health concerns", "Routine check-ups", "Preventive care", "Common illnesses", "Minor injuries", "Immunizations", "Chronic disease management", "Health counseling", "Health promotion", "Patient education", "Nutrition advice", "Stress management", "Mental health support", "Women's health", "Men's health", "Pediatric care", "Geriatric care", "Family planning", "Weight management", "Smoking cessation"],
        "Internal Medicine Physician": ["Complex medical conditions", "Chronic diseases", "Internal organ disorders", "Preventive care", "Diagnostic tests", "Medication management", "Cardiovascular diseases", "Gastrointestinal disorders", "Endocrine disorders", "Infectious diseases", "Respiratory diseases", "Immunizations", "Mental health issues", "Nutrition counseling", "Weight management", "Routine check-ups", "Health screenings", "Blood pressure management", "Diabetes care", "Cholesterol management"],
        "Pediatrician": ["Childhood vaccinations", "Developmental milestones", "Growth monitoring", "Common childhood illnesses", "Behavioral issues", "Learning disabilities", "Nutrition advice", "Immunizations", "Childhood infections", "Ear infections", "Respiratory infections", "Allergies", "Asthma", "Childhood obesity", "Adolescent health", "Routine check-ups", "Vision and hearing screenings", "Developmental screenings", "Speech and language development", "Childhood injuries"],
        "Geriatric Medicine Doctors": ["Age-related health concerns", "Chronic diseases in the elderly", "Memory issues", "Fall prevention", "Medication management", "Osteoporosis", "Arthritis", "Hearing and vision problems", "Incontinence", "Nutrition in the elderly", "End-of-life care", "Palliative care", "Alzheimer's disease", "Dementia", "Depression in the elderly", "Routine check-ups", "Cancer screenings", "Vaccinations for the elderly", "Mobility issues", "Sleep disorders"],
        "Allergists": ["Allergic rhinitis", "Asthma", "Sinusitis", "Food allergies", "Drug allergies", "Insect sting allergies", "Atopic dermatitis (eczema)", "Contact dermatitis", "Hives (urticaria)", "Anaphylaxis", "Immunotherapy", "Patch testing", "Nasal endoscopy", "Spirometry", "Skin prick tests", "Blood tests for allergies", "Environmental allergies", "Allergy medications", "Allergy desensitization", "Allergy prevention"],
        "Dermatologists": ["Acne", "Eczema", "Psoriasis", "Rosacea", "Skin cancer screenings", "Moles and skin lesions", "Warts", "Hair loss", "Nail disorders", "Skin infections", "Allergic skin reactions", "Cysts and lipomas", "Melasma", "Vitiligo", "Dermatitis", "Aging skin", "Sun damage", "Cosmetic dermatology", "Laser therapy", "Chemical peels"],
        "Infectious Disease Doctors": ["Bacterial infections", "Viral infections", "Fungal infections", "Parasitic infections", "HIV/AIDS", "Sexually transmitted infections (STIs)", "Tuberculosis", "Infectious mononucleosis", "Influenza", "Hepatitis", "Meningitis", "Sepsis", "Antibiotic therapy", "Immunizations", "Travel medicine", "Preventive measures", "Epidemiology", "Infection control", "Outbreak management", "Post-exposure prophylaxis (PEP)"],
        "Ophthalmologists": ["Vision problems", "Eye exams", "Prescription for eyeglasses or contact lenses", "Cataracts", "Glaucoma", "Macular degeneration", "Diabetic retinopathy", "Retinal detachment", "Conjunctivitis (pink eye)", "Dry eyes", "Corneal diseases", "Strabismus", "Amblyopia", "Refractive surgery (LASIK)", "Eye injuries", "Uveitis", "Blepharitis", "Ptosis", "Retinitis pigmentosa", "Ocular oncology"],
        "Obstetrician/Gynecologists": ["Prenatal care", "Childbirth", "Postpartum care", "Family planning", "Contraception", "Menstrual disorders", "Pelvic pain", "Endometriosis", "Polycystic ovary syndrome (PCOS)", "Sexually transmitted infections (STIs)", "Uterine fibroids", "Ovarian cysts", "Cervical dysplasia", "Menopause management", "Hormone replacement therapy", "Infertility", "Pelvic organ prolapse", "Urinary incontinence", "Gynecological cancers", "Sexual health"],
        "Cardiologists": ["Coronary artery disease", "Heart failure", "Heart attack", "Arrhythmias", "Valvular heart disease", "Hypertension", "High cholesterol", "Peripheral artery disease", "Atherosclerosis", "Cardiomyopathy", "Congenital heart defects", "Electrocardiogram (ECG or EKG)", "Echocardiogram", "Holter monitor", "Stress test", "Cardiac catheterization", "Angioplasty", "Coronary artery bypass grafting (CABG)", "Implantable cardioverter-defibrillator (ICD)", "Pacemaker"],
        "Endocrinologists": ["Diabetes mellitus", "Thyroid disorders", "Hormone imbalances", "Metabolic disorders", "Osteoporosis", "Pituitary disorders", "Adrenal disorders", "Polycystic ovary syndrome (PCOS)", "Hypoglycemia", "Hyperglycemia", "Growth disorders", "Obesity management", "Lipid disorders", "Menopause management", "Infertility due to hormonal issues", "Calcium and vitamin D disorders", "Endocrine tumors", "Thyroid cancer", "Adrenal tumors", "Pituitary tumors"],
        "Gastroenterologists": ["Gastroesophageal reflux disease (GERD)", "Irritable bowel syndrome (IBS)", "Inflammatory bowel disease (IBD)", "Crohn's disease", "Ulcerative colitis", "Celiac disease", "Peptic ulcers", "Gastritis", "Liver diseases", "Hepatitis", "Cirrhosis", "Pancreatitis", "Gallstones", "Diverticulitis", "Colon polyps", "Colon cancer screenings", "Gastrointestinal bleeding", "Hemorrhoids", "Bowel obstruction", "Malabsorption disorders"],
        "Nephrologists": ["Chronic kidney disease","Acute kidney injury","Kidney stones",
        "Hypertension-related kidney issues",
        "Diabetic nephropathy",
        "Glomerulonephritis",
        "Polycystic kidney disease",
        "Nephrotic syndrome",
        "Renal artery stenosis",
        "Electrolyte imbalances",
        "Acid-base imbalances",
        "Proteinuria",
        "Hematuria",
        "Renal cysts",
        "Hydronephrosis",
        "Urinary tract infections affecting the kidneys",
        "Pre- and post-kidney transplant care",
        "Drug-induced kidney damage",
        "Systemic diseases affecting the kidneys (e.g., lupus)",
        "Genetic kidney disorders"],"Urologists": [
            "Blood in urine (hematuria)",
            "Painful urination",
            "Frequent urination",
            "Urinary incontinence",
            "Erectile dysfunction",
            "Prostate issues",
            "Kidney stones",
            "Urinary tract infections",
            "Testicular pain or swelling",
            "Bladder control problems",
            "Pelvic pain",
            "Difficulty starting or maintaining urine flow",
            "Prostate enlargement (BPH)",
            "Male infertility",
            "Prostatitis",
            "Bladder or kidney cancer symptoms",
            "Hydronephrosis",
            "Interstitial cystitis",
            "Overactive bladder",
            "Urinary retention"
        ],
        "Pulmonologists": [
            "Shortness of breath",
            "Persistent cough",
            "Wheezing",
            "Chest pain or discomfort",
            "Chronic bronchitis symptoms",
            "Chest tightness",
            "Coughing up blood",
            "Fatigue",
            "Frequent respiratory infections",
            "Difficulty breathing with exertion",
            "Rapid breathing",
            "Cyanosis (bluish tint to lips or fingertips)",
            "Chronic obstructive pulmonary disease (COPD)",
            "Asthma exacerbation",
            "Interstitial lung disease",
            "Pneumonia symptoms",
            "Lung cancer symptoms",
            "Pulmonary fibrosis",
            "Sleep apnea symptoms",
            "Pleuritic chest pain"
        ],
        "Otolaryngologists": [
            "Hearing loss",
            "Ear pain or infections",
            "Tinnitus (ringing in the ears)",
            "Vertigo or dizziness",
            "Nasal congestion",
            "Sinus pain or infections",
            "Chronic sore throat",
            "Hoarseness",
            "Swallowing difficulties",
            "Neck masses or lumps",
            "Enlarged tonsils or adenoids",
            "Snoring",
            "Sleep apnea",
            "Thyroid nodules",
            "Facial pain or pressure",
            "Allergies affecting the ears, nose, or throat",
            "Voice changes",
            "Laryngitis",
            "Salivary gland disorders",
            "Head and neck cancers"
        ],
        "Neurologists": [
            "Headaches or migraines",
            "Seizures or convulsions",
            "Dizziness or lightheadedness",
            "Numbness or tingling in limbs",
            "Muscle weakness",
            "Difficulty walking or coordination problems",
            "Memory loss or confusion",
            "Vision problems",
            "Speech difficulties",
            "Tremors or shaking",
            "Chronic pain syndromes",
            "Movement disorders (e.g., Parkinson's disease)",
            "Multiple sclerosis symptoms",
            "Peripheral neuropathy",
            "Cognitive impairment",
            "Vertigo",
            "Neck or back pain radiating to limbs",
            "Restless legs syndrome",
            "Bell's palsy",
            "Neurological complications of systemic diseases"
        ],
        "Psychiatrists": [
            "Depression",
            "Anxiety disorders",
            "Panic attacks",
            "Obsessive-compulsive disorder (OCD)",
            "Post-traumatic stress disorder (PTSD)",
            "Bipolar disorder",
            "Schizophrenia",
            "Eating disorders",
            "Sleep disorders",
            "Substance abuse or addiction",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Personality disorders",
            "Mood swings",
            "Suicidal thoughts",
            "Self-harm behaviors",
            "Phobias",
            "Psychotic symptoms",
            "Impulse control disorders",
            "Psychosomatic disorders",
            "Autism spectrum disorders"
        ],
        "Oncologists": [
            "Unexplained weight loss",
            "Fatigue",
            "Lumps or masses",
            "Pain that doesn't go away",
            "Changes in skin color or texture",
            "Changes in bowel or bladder habits",
            "Persistent cough or hoarseness",
            "Difficulty swallowing",
            "Chronic indigestion or heartburn",
            "Persistent infections",
            "Bruising easily",
            "Enlarged lymph nodes",
            "Unexplained fevers",
            "Night sweats",
            "Changes in mole appearance",
            "Abnormal bleeding",
            "Bone pain",
            "Neurological symptoms",
            "Shortness of breath",
            "Swelling or fluid retention"
        ],
        "Radiologists": [
            "Abnormal imaging findings",
            "Unexplained pain",
            "Tumors or masses",
            "Fractures",
            "Blood vessel abnormalities",
            "Organ abnormalities",
            "Joint problems",
            "Digestive system issues",
            "Respiratory system issues",
            "Cardiovascular abnormalities",
            "Neurological abnormalities",
            "Kidney or bladder abnormalities",
            "Reproductive system abnormalities",
            "Breast abnormalities",
            "Thyroid abnormalities",
            "Soft tissue abnormalities",
            "Bone density issues",
            "Screening for cancer",
            "Monitoring treatment response",
            "Assessment of trauma"
        ],
        "Rheumatologists": [
            "Joint pain",
            "Joint swelling",
            "Joint stiffness",
            "Muscle pain",
            "Fatigue",
            "Fever",
            "Morning stiffness",
            "Loss of joint function",
            "Numbness or tingling in extremities",
            "Skin rashes",
            "Photosensitivity",
            "Raynaud's phenomenon",
            "Joint deformities",
            "Tender joints",
            "Dry eyes or mouth",
            "Difficulty concentrating",
            "Chest pain with breathing",
            "Hair loss",
            "Swollen glands",
            "Difficulty sleeping"
        ],
        "General Surgeons": [
            "Abdominal pain",
            "Digestive system issues",
            "Appendicitis symptoms",
            "Hernias",
            "Gallbladder problems",
            "Bowel obstruction symptoms",
            "Gastrointestinal bleeding",
            "Thyroid nodules or tumors",
            "Soft tissue masses or lumps",
            "Skin cancer or lesions",
            "Breast lumps or abnormalities",
            "Swollen lymph nodes",
            "Hemorrhoids",
            "Varicose veins",
            "Lumps or masses in any part of the body",
            "Biopsy procedures",
            "Incision and drainage of abscesses",
            "Wound care",
            "Laparoscopic procedures",
            "Treatment of traumatic injuries"
        ],"Orthopedic Surgeons": [
            "Joint pain",
            "Joint swelling",
            "Joint stiffness",
            "Limited range of motion",
            "Muscle weakness",
            "Fractures or dislocations",
            "Back pain",
            "Neck pain",
            "Shoulder pain",
            "Hip pain",
            "Knee pain",
            "Foot and ankle pain",
            "Tenderness around joints",
            "Crepitus (joint popping or grinding)",
            "Deformities in bones or joints",
            "Difficulty walking",
            "Numbness or tingling in limbs",
            "Loss of sensation",
            "Muscle spasms",
            "Sports injuries"
        ],
        "Cardiac Surgeons": [
            "Chest pain or discomfort",
            "Shortness of breath",
            "Fatigue",
            "Irregular heartbeat",
            "Dizziness or fainting",
            "Swelling in the legs or ankles",
            "Nausea or vomiting",
            "Sweating",
            "Pain or discomfort in the arms, neck, jaw, or back",
            "High blood pressure",
            "Palpitations",
            "Difficulty exercising",
            "Fluid retention",
            "Blue or purple discoloration of lips or extremities",
            "Heart murmur",
            "Valvular heart disease symptoms",
            "Aortic aneurysm symptoms",
            "Heart failure symptoms",
            "Coronary artery disease symptoms",
            "Pericarditis symptoms"
        ],
        "Anesthesiologists": [
            "Preoperative assessment",
            "Intraoperative pain management",
            "Postoperative pain management",
            "Nausea and vomiting after surgery",
            "Difficulty breathing after surgery",
            "Fatigue or weakness after surgery",
            "Confusion or disorientation after surgery",
            "Chronic pain conditions",
            "Anesthesia side effects",
            "Allergic reactions to anesthesia",
            "Difficulty waking up after surgery",
            "Muscle aches or soreness after surgery",
            "Infection at the surgical site",
            "Blood clot symptoms",
            "Nerve damage",
            "Headache after spinal anesthesia",
            "Respiratory complications after surgery",
            "Hypotension or hypertension during surgery",
            "Anesthesia awareness",
            "Monitoring and management of vital signs"
        ],
        "Family Medicine": [
            "Routine check-ups",
            "Immunizations",
            "Minor injuries",
            "Cough and cold symptoms",
            "Fever",
            "Headaches",
            "Earaches",
            "Sore throat",
            "Respiratory infections",
            "Gastrointestinal issues",
            "High blood pressure",
            "Cholesterol management",
            "Diabetes management",
            "Weight management",
            "Nutrition counseling",
            "Women's health",
            "Men's health",
            "Mental health concerns",
            "Anxiety",
            "Depression"
        ],
        "Internal Medicine": [
            "Chronic diseases",
            "Diabetes",
            "High blood pressure",
            "High cholesterol",
            "Thyroid disorders",
            "Respiratory issues",
            "Gastrointestinal problems",
            "Liver disorders",
            "Kidney diseases",
            "Infectious diseases",
            "Autoimmune diseases",
            "Arthritis",
            "Osteoporosis",
            "Allergies",
            "Hormonal imbalances",
            "Weight management",
            "Preventive care",
            "Cancer screenings",
            "Menopause management"
        ],
        "Pediatrician": [
            "Growth and development concerns",
            "Immunizations",
            "Feeding difficulties",
            "Sleep problems",
            "Respiratory infections",
            "Ear infections",
            "Allergies",
            "Asthma",
            "Skin rashes or irritations",
            "Behavioral issues",
            "Learning disabilities",
            "Childhood obesity",
            "Vision or hearing problems",
            "Childhood vaccinations",
            "Developmental milestones",
            "Adolescent health concerns",
            "Chronic illnesses in children",
            "Infections",
            "Nutrition advice",
            "Genetic or congenital conditions"
        ],
        "Obstetricians/Gynecologists (OBGYNs)": [
            "Menstrual irregularities",
            "Pelvic pain",
            "Endometriosis",
            "Polycystic ovary syndrome (PCOS)",
            "Menopausal symptoms",
            "Pregnancy-related concerns",
            "Infertility",
            "Birth control management",
            "Sexually transmitted infections (STIs)",
            "Breast health concerns",
            "Cervical abnormalities",
            "Uterine fibroids",
            "Ovarian cysts",
            "Pelvic inflammatory disease (PID)",
            "Vaginal infections",
            "Sexual dysfunction",
            "Pelvic organ prolapse",
            "Gynecological cancers",
            "Preconception counseling",
            "Prenatal care"
        ],
        "Cardiologist": [
            "Chest pain or discomfort",
            "Shortness of breath",
            "Fatigue",
            "Irregular heartbeat",
            "Dizziness or fainting",
            "Swelling in the legs or ankles",
            "Nausea or vomiting",
            "Sweating",
            "High blood pressure",
            "Palpitations",
            "Atherosclerosis",
            "Heart murmurs",
            "Valvular heart disease",
            "Coronary artery disease",
            "Heart failure",
            "Cardiomyopathy",
            "Peripheral artery disease",
            "Cardiac arrhythmias",
            "Angina",
            "Congenital heart defects"
        ],
        "Oncologist": [
            "Unexplained weight loss",
            "Fatigue",
            "Lumps or masses",
            "Pain that doesn't go away",
            "Changes in skin color or texture",
            "Changes in bowel or bladder habits",
            "Persistent cough or hoarseness",
            "Difficulty swallowing",
            "Chronic indigestion or heartburn",
            "Persistent infections",
            "Bruising easily",
            "Enlarged lymph nodes",
            "Unexplained fevers",
            "Night sweats",
            "Changes in mole appearance",
            "Abnormal bleeding",
            "Bone pain",
            "Neurological symptoms",
            "Shortness of breath",
            "Swelling or fluid retention"
        ],"Gastroenterologist": [
            "Abdominal pain",
            "Digestive issues",
            "Heartburn or acid reflux",
            "Bloating",
            "Nausea or vomiting",
            "Diarrhea",
            "Constipation",
            "Blood in stool",
            "Unexplained weight loss",
            "Difficulty swallowing",
            "Gastrointestinal bleeding",
            "Gallbladder issues",
            "Liver disorders",
            "Inflammatory bowel disease (IBD)",
            "Irritable bowel syndrome (IBS)",
            "Celiac disease symptoms",
            "Pancreatitis",
            "Gastrointestinal infections",
            "Colon polyps",
            "Colon cancer symptoms"
        ],
        "Pulmonologist": [
            "Shortness of breath",
            "Persistent cough",
            "Wheezing",
            "Chest pain or discomfort",
            "Chronic bronchitis symptoms",
            "Chest tightness",
            "Coughing up blood",
            "Fatigue",
            "Frequent respiratory infections",
            "Difficulty breathing with exertion",
            "Rapid breathing",
            "Cyanosis (bluish tint to lips or fingertips)",
            "Chronic obstructive pulmonary disease (COPD)",
            "Asthma exacerbation",
            "Interstitial lung disease",
            "Pneumonia symptoms",
            "Lung cancer symptoms",
            "Pulmonary fibrosis",
            "Sleep apnea symptoms",
            "Pleuritic chest pain"
        ],
        "Infectious Disease": [
            "Fever",
            "Fatigue",
            "Chills",
            "Sweating",
            "Muscle aches or joint pain",
            "Headache",
            "Cough",
            "Shortness of breath",
            "Diarrhea",
            "Nausea or vomiting",
            "Abdominal pain",
            "Skin rashes",
            "Enlarged lymph nodes",
            "Sore throat",
            "Urinary symptoms",
            "Eye redness or discharge",
            "Unexplained weight loss",
            "Night sweats",
            "Persistent infections",
            "Travel-related illnesses"
        ],
        "Nephrologist": [
            "Chronic kidney disease",
            "Acute kidney injury",
            "Kidney stones",
            "Hypertension-related kidney issues",
            "Diabetic nephropathy",
            "Glomerulonephritis",
            "Polycystic kidney disease",
            "Nephrotic syndrome",
            "Renal artery stenosis",
            "Electrolyte imbalances",
            "Acid-base imbalances",
            "Proteinuria",
            "Hematuria",
            "Renal cysts",
            "Hydronephrosis",
            "Urinary tract infections affecting the kidneys",
            "Pre- and post-kidney transplant care",
            "Drug-induced kidney damage",
            "Systemic diseases affecting the kidneys (e.g., lupus)",
            "Genetic kidney disorders"
        ],
        "Endocrinologist": [
            "Diabetes mellitus",
            "Thyroid disorders",
            "Hormone imbalances",
            "Metabolic disorders",
            "Osteoporosis",
            "Pituitary disorders",
            "Adrenal disorders",
            "Polycystic ovary syndrome (PCOS)",
            "Hypoglycemia",
            "Hyperglycemia",
            "Growth disorders",
            "Obesity management",
            "Lipid disorders",
            "Menopause management",
            "Infertility due to hormonal issues",
            "Calcium and vitamin D disorders",
            "Endocrine tumors",
            "Thyroid cancer",
            "Adrenal tumors",
            "Pituitary tumors"
        ],
        "Ophthalmologist": [
            "Vision problems",
            "Eye pain or discomfort",
            "Red or bloodshot eyes",
            "Eye injuries",
            "Floaters or flashes of light",
            "Double vision",
            "Dry eyes",
            "Watery eyes",
            "Blurry or distorted vision",
            "Sensitivity to light",
            "Eye twitching",
            "Bulging eyes",
            "Color vision problems",
            "Night blindness",
            "Halos around lights",
            "Crossed eyes",
            "Lazy eye",
            "Itchy or burning eyes",
            "Styes or chalazia",
            "Conjunctivitis (pink eye)"
        ],
        "Otolaryngologist": [
            "Hearing loss",
            "Ear pain or infections",
            "Tinnitus (ringing in the ears)",
            "Vertigo or dizziness",
            "Nasal congestion",
            "Sinus pain or infections",
            "Chronic sore throat",
            "Hoarseness",
            "Swallowing difficulties",
            "Neck masses or lumps",
            "Enlarged tonsils or adenoids",
            "Snoring",
            "Sleep apnea",
            "Thyroid nodules",
            "Facial pain or pressure",
            "Allergies affecting the ears, nose, or throat",
            "Voice changes",
            "Laryngitis",
            "Salivary gland disorders",
            "Head and neck cancers"
        ],
        "Dermatologist": [
            "Acne",
            "Eczema",
            "Psoriasis",
            "Rosacea",
            "Skin cancer screenings",
            "Moles and skin lesions",
            "Warts",
            "Hair loss",
            "Nail disorders",
            "Skin infections",
            "Allergic skin reactions",
            "Cysts and lipomas",
            "Melasma",
            "Vitiligo",
            "Dermatitis",
            "Aging skin",
            "Sun damage",
            "Cosmetic dermatology",
            "Laser therapy",
            "Chemical peels"
        ],
        "Psychiatrist": [
            "Depression",
            "Anxiety disorders",
            "Panic attacks",
            "Obsessive-compulsive disorder (OCD)",
            "Post-traumatic stress disorder (PTSD)",
            "Bipolar disorder",
            "Schizophrenia",
            "Eating disorders",
            "Sleep disorders",
            "Substance abuse or addiction",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Personality disorders",
            "Mood swings",
            "Suicidal thoughts",
            "Self-harm behaviors",
            "Phobias",
            "Psychotic symptoms",
            "Impulse control disorders",
            "Psychosomatic disorders",
            "Autism spectrum disorders"
        ],"Neurologist": [
            "Headaches or migraines",
            "Seizures or convulsions",
            "Dizziness or lightheadedness",
            "Numbness or tingling in limbs",
            "Muscle weakness",
            "Difficulty walking or coordination problems",
            "Memory loss or confusion",
            "Vision problems",
            "Speech difficulties",
            "Tremors or shaking",
            "Chronic pain syndromes",
            "Movement disorders (e.g., Parkinson's disease)",
            "Multiple sclerosis symptoms",
            "Peripheral neuropathy",
            "Cognitive impairment",
            "Vertigo",
            "Neck or back pain radiating to limbs",
            "Restless legs syndrome",
            "Bell's palsy",
            "Neurological complications of systemic diseases"
        ],
        "Radiologist": [
            "Abnormal imaging findings",
            "Unexplained pain",
            "Tumors or masses",
            "Fractures",
            "Blood vessel abnormalities",
            "Organ abnormalities",
            "Joint problems",
            "Digestive system issues",
            "Respiratory system issues",
            "Cardiovascular abnormalities",
            "Neurological abnormalities",
            "Kidney or bladder abnormalities",
            "Reproductive system abnormalities",
            "Breast abnormalities",
            "Thyroid abnormalities",
            "Soft tissue abnormalities",
            "Bone density issues",
            "Screening for cancer",
            "Monitoring treatment response",
            "Assessment of trauma"
        ],
        "Anesthesiologist": [
            "Preoperative assessment",
            "Intraoperative pain management",
            "Postoperative pain management",
            "Nausea and vomiting after surgery",
            "Difficulty breathing after surgery",
            "Fatigue or weakness after surgery",
            "Confusion or disorientation after surgery",
            "Chronic pain conditions",
            "Anesthesia side effects",
            "Allergic reactions to anesthesia",
            "Difficulty waking up after surgery",
            "Muscle aches or soreness after surgery",
            "Infection at the surgical site",
            "Blood clot symptoms",
            "Nerve damage",
            "Headache after spinal anesthesia",
            "Respiratory complications after surgery",
            "Hypotension or hypertension during surgery",
            "Anesthesia awareness",
            "Monitoring and management of vital signs"
        ],
        "Surgeon": [
            "Abdominal pain",
            "Digestive system issues",
            "Appendicitis symptoms",
            "Hernias",
            "Gallbladder problems",
            "Bowel obstruction symptoms",
            "Gastrointestinal bleeding",
            "Thyroid nodules or tumors",
            "Soft tissue masses or lumps",
            "Skin cancer or lesions",
            "Breast lumps or abnormalities",
            "Swollen lymph nodes",
            "Hemorrhoids",
            "Varicose veins",
            "Lumps or masses in any part of the body",
            "Biopsy procedures",
            "Incision and drainage of abscesses",
            "Wound care",
            "Laparoscopic procedures",
            "Treatment of traumatic injuries"
        ],
        "Physician Executive": [
            "Healthcare administration",
            "Strategic planning in healthcare",
            "Quality improvement initiatives",
            "Healthcare policy development",
            "Patient safety programs",
            "Budgeting and financial management",
            "Medical staff management",
            "Implementation of healthcare technologies",
            "Population health management",
            "Risk management",
            "Medical ethics",
            "Healthcare regulations compliance",
            "Interdisciplinary collaboration",
            "Leadership development",
            "Healthcare workforce management",
            "Healthcare innovation",
            "Patient experience improvement",
            "Medical education programs",
            "Community outreach",
            "Value-based care initiatives"
        ],
        "Addiction Medicine Specialist": [
            "Substance abuse",
            "Alcohol addiction",
            "Drug addiction",
            "Prescription medication dependence",
            "Opioid addiction",
            "Nicotine addiction",
            "Behavioral addictions",
            "Gambling addiction",
            "Internet or gaming addiction",
            "Compulsive overeating",
            "Dual diagnosis (co-occurring mental health and addiction issues)",
            "Detoxification",
            "Rehabilitation programs",
            "Relapse prevention",
            "Counseling and therapy",
            "12-step programs",
            "Medication-assisted treatment",
            "Support groups",
            "Family interventions",
            "Community resources for addiction recovery"
        ],
        "Adolescent Medicine Specialist": [
            "Teenage acne",
            "Menstrual irregularities in adolescents",
            "Adolescent growth and development concerns",
            "Eating disorders in teenagers",
            "Behavioral issues",
            "Teenage depression",
            "Anxiety in adolescents",
            "Teenage substance abuse",
            "Reproductive health education",
            "Teenage pregnancy",
            "Sexually transmitted infections (STIs) in adolescents",
            "Vaccination schedules for adolescents",
            "Adolescent nutrition and fitness",
            "Adolescent sleep disorders",
            "School-related stress",
            "Sports-related injuries in adolescents",
            "Adolescent immunizations",
            "Mood disorders in teenagers",
            "Adolescent preventive healthcare",
            "Parenting strategies for teenagers"
        ],
        "Allergist (Immunologist)": [
            "Seasonal allergies",
            "Year-round allergies",
            "Allergic rhinitis",
            "Asthma triggered by allergies",
            "Hives (urticaria)",
            "Eczema (atopic dermatitis)",
            "Food allergies",
            "Drug allergies",
            "Insect sting allergies",
            "Latex allergies",
            "Allergic reactions to vaccines",
            "Immunodeficiency disorders",
            "Autoimmune disorders with allergic manifestations",
            "Patch testing for contact dermatitis",
            "Anaphylaxis",
            "Sinusitis caused by allergies",
            "Atopic march (progression of allergic diseases)",
            "Desensitization (immunotherapy) for allergies",
            "Allergy testing and diagnosis",
            "Allergic conjunctivitis"
        ],
        "Anatomic Pathologist": [
            "Analysis of tissue specimens",
            "Biopsy interpretation",
            "Surgical pathology",
            "Cytopathology",
            "Autopsy pathology",
            "Immunohistochemistry",
            "Molecular pathology",
            "Pathological examination of organs",
            "Diagnosis of cancer",
            "Identification of infectious diseases",
            "Evaluation of inflammatory conditions",
            "Assessment of tissue changes in response to therapy",
            "Identification of genetic disorders",
            "Forensic pathology",
            "Tumor grading and staging",
            "Evaluation of lymph node specimens",
            "Analysis of bone marrow samples",
            "Diagnosis of skin disorders",
            "Contributing to medical research",
            "Educational roles in medical institutions"
        ],"Cardiac Electrophysiologist": [
            "Irregular heartbeat (arrhythmia)",
            "Palpitations",
            "Dizziness or lightheadedness",
            "Fainting or syncope",
            "Chest pain or discomfort",
            "Shortness of breath",
            "Fatigue",
            "Rapid heart rate (tachycardia)",
            "Slow heart rate (bradycardia)",
            "Fluttering in the chest",
            "Atrial fibrillation symptoms",
            "Atrial flutter symptoms",
            "Supraventricular tachycardia (SVT) symptoms",
            "Ventricular tachycardia symptoms",
            "Ventricular fibrillation symptoms",
            "Heart block symptoms",
            "Pacemaker-related issues",
            "Implantable cardioverter-defibrillator (ICD) issues",
            "Electrophysiology studies",
            "Cardiac ablation procedures"
        ],
        "Cardiovascular Surgeon": [
            "Chest pain or discomfort",
            "Shortness of breath",
            "Fatigue",
            "Irregular heartbeat",
            "Dizziness or fainting",
            "Swelling in the legs or ankles",
            "Nausea or vomiting",
            "Sweating",
            "Pain or discomfort in the arms, neck, jaw, or back",
            "Heart murmurs",
            "Valvular heart disease symptoms",
            "Coronary artery disease symptoms",
            "Aortic aneurysm symptoms",
            "Peripheral artery disease symptoms",
            "Congenital heart defects",
            "Heart failure symptoms",
            "Cardiomyopathy symptoms",
            "Heart transplant evaluation",
            "Vascular surgery needs",
            "Thoracic aortic disease symptoms"
        ],
        "Clinical Laboratory Immunologist": [
            "Frequent infections",
            "Recurrent respiratory infections",
            "Unexplained fevers",
            "Persistent sore throat",
            "Swollen lymph nodes",
            "Chronic fatigue",
            "Autoimmune disease symptoms",
            "Allergic reactions",
            "Immunodeficiency disorders",
            "Inflammatory disorders",
            "Rheumatoid arthritis symptoms",
            "Lupus symptoms",
            "Multiple sclerosis symptoms",
            "Chronic diarrhea",
            "Eczema or dermatitis",
            "Celiac disease symptoms",
            "Allergy testing and diagnosis",
            "Monitoring of immunosuppressive therapy",
            "Evaluation of abnormal blood counts",
            "Diagnosis of primary immunodeficiencies"
        ],
        "Colon and Rectal Surgeon": [
            "Abdominal pain or discomfort",
            "Change in bowel habits",
            "Blood in stool",
            "Rectal bleeding",
            "Anal pain or itching",
            "Constipation",
            "Diarrhea",
            "Unexplained weight loss",
            "Abdominal bloating",
            "Colon polyps",
            "Inflammatory bowel disease (IBD) symptoms",
            "Diverticulitis symptoms",
            "Colon cancer symptoms",
            "Anal fissures",
            "Hemorrhoids",
            "Fecal incontinence",
            "Rectal prolapse",
            "Colonoscopy abnormalities",
            "Screening for colorectal cancer",
            "Treatment of colorectal diseases"
        ],
        "Critical Care Medicine Specialist": [
            "Respiratory distress or failure",
            "Shock",
            "Septicemia (sepsis)",
            "Multiple organ failure",
            "Severe trauma",
            "Burn injuries",
            "Major surgical complications",
            "Cardiac arrest",
            "Severe infections",
            "Acute respiratory distress syndrome (ARDS)",
            "Hemodynamic instability",
            "Life-threatening electrolyte imbalances",
            "Complications of severe illnesses",
            "Management of critically ill patients",
            "Advanced life support",
            "Mechanical ventilation",
            "Hemodynamic monitoring",
            "Acute kidney injury",
            "Neurological emergencies",
            "Management of postoperative complications"
        ],
        "Cytopathologist": [
            "Abnormal Pap smear results",
            "Unexplained weight loss",
            "Lumps or masses",
            "Tumors or cysts",
            "Fluid-filled cavities (effusions)",
            "Thyroid nodules",
            "Biopsy interpretation",
            "Fine-needle aspiration (FNA) biopsy",
            "Evaluation of body fluids (pleural, pericardial, etc.)",
            "Screening for cancer",
            "Diagnosis of precancerous lesions",
            "Cervical dysplasia",
            "Detection of infectious agents in cells",
            "Ascitic fluid analysis",
            "Cerebrospinal fluid (CSF) analysis",
            "Urinary cytology",
            "Cellular changes indicating malignancy",
            "Identification of atypical or abnormal cells",
            "Contribution to cancer staging",
            "Consultation with other pathologists and clinicians"
        ],
        "Dermatopathologist": [
            "Skin rashes",
            "Moles and skin lesions",
            "Eczema",
            "Psoriasis",
            "Acne",
            "Skin infections",
            "Blistering disorders",
            "Hair loss",
            "Nail disorders",
            "Vasculitis affecting the skin",
            "Connective tissue diseases affecting the skin",
            "Skin cancer screening",
            "Melanoma",
            "Basal cell carcinoma",
            "Squamous cell carcinoma",
            "Lymphoma involving the skin",
            "Cutaneous manifestations of systemic diseases",
            "Mycosis fungoides",
            "Granulomatous skin diseases",
            "Genodermatoses"
        ],
        "Developmental Pediatrician": [
            "Speech and language delays",
            "Motor skill delays",
            "Social and emotional delays",
            "Learning difficulties",
            "Behavioral concerns",
            "Autism spectrum disorders",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Intellectual disabilities",
            "Genetic disorders affecting development",
            "Developmental regression",
            "Feeding difficulties",
            "Sleep disturbances",
            "School-related challenges",
            "Physical developmental delays",
            "Cerebral palsy",
            "Epilepsy in children",
            "Sensory processing issues",
            "Global developmental delay",
            "Neurodevelopmental disorders",
            "Family counseling and support"
        ],
        "Emergency Medicine Specialist": [
            "Chest pain or discomfort",
            "Shortness of breath",
            "Severe abdominal pain",
            "Suspected heart attack or stroke",
            "Traumatic injuries",
            "Broken bones",
            "Head injuries",
            "Burn injuries",
            "Seizures or convulsions",
            "Sudden and severe headaches",
            "Unexplained fainting or dizziness",
            "Allergic reactions",
            "Severe allergic symptoms (anaphylaxis)",
            "Severe bleeding",
            "High fever with confusion",
            "Infections requiring immediate attention",
            "Suspected poisoning or overdose",
            "Difficulty breathing",
            "Uncontrolled bleeding",
            "Sudden and severe pain"
        ],"Endocrinologist": [
            "Fatigue",
            "Unexplained weight changes",
            "Thyroid disorders",
            "Diabetes mellitus",
            "Hormone imbalances",
            "Metabolic disorders",
            "Osteoporosis",
            "Pituitary disorders",
            "Adrenal disorders",
            "Polycystic ovary syndrome (PCOS)",
            "Hypoglycemia",
            "Hyperglycemia",
            "Growth disorders",
            "Obesity management",
            "Lipid disorders",
            "Menopause symptoms",
            "Infertility due to hormonal issues",
            "Calcium and vitamin D disorders",
            "Endocrine tumors",
            "Thyroid cancer"
        ],
        "Forensic Pathologist": [
            "Unexplained deaths",
            "Suspicious or violent deaths",
            "Autopsy analysis",
            "Postmortem examinations",
            "Identification of cause of death",
            "Determination of manner of death (homicide, suicide, accident, natural causes)",
            "Analysis of injuries and trauma",
            "Identification of toxins or drugs in the body",
            "Examination of skeletal remains",
            "Expert testimony in legal cases",
            "Documentation of injuries for legal purposes",
            "Evaluation of decomposed or mutilated bodies",
            "Identification of victims in mass disasters",
            "Child abuse investigations",
            "Documentation of evidence in criminal cases",
            "Consultation with law enforcement agencies",
            "Documentation of evidence for insurance claims",
            "Collaboration with other forensic specialists",
            "Analysis of firearm injuries",
            "Investigation of sudden or unexpected deaths"
        ],
        "Gastroenterologist": [
            "Abdominal pain",
            "Digestive issues",
            "Heartburn or acid reflux",
            "Bloating",
            "Nausea or vomiting",
            "Diarrhea",
            "Constipation",
            "Blood in stool",
            "Unexplained weight loss",
            "Difficulty swallowing",
            "Gastrointestinal bleeding",
            "Gallbladder issues",
            "Liver disorders",
            "Inflammatory bowel disease (IBD)",
            "Irritable bowel syndrome (IBS)",
            "Celiac disease symptoms",
            "Pancreatitis",
            "Gastrointestinal infections",
            "Colon polyps",
            "Colon cancer symptoms"
        ],
        "Geriatric Psychiatrist": [
            "Memory loss",
            "Cognitive decline",
            "Alzheimer's disease symptoms",
            "Dementia symptoms",
            "Depression in older adults",
            "Anxiety in older adults",
            "Behavioral changes",
            "Sleep disturbances",
            "Psychotic symptoms in the elderly",
            "Delirium",
            "Mood disorders",
            "Medication management in older adults",
            "Grief and loss issues",
            "Adjustment disorders",
            "Social isolation",
            "Caregiver stress",
            "End-of-life issues",
            "Psychiatric symptoms related to chronic medical conditions",
            "Capacity assessments",
            "Quality of life assessments"
        ],
        "Hand Surgeon": [
            "Hand pain",
            "Wrist pain",
            "Carpal tunnel syndrome symptoms",
            "Tendonitis or tenosynovitis",
            "Numbness or tingling in the hands",
            "Trigger finger",
            "Hand or finger fractures",
            "Arthritis in the hands",
            "Dupuytren's contracture",
            "Ganglion cysts",
            "De Quervain's tenosynovitis",
            "Hand or finger infections",
            "Hand or finger deformities",
            "Hand or finger swelling",
            "Hand or finger weakness",
            "Repetitive strain injuries",
            "Hand or finger dislocations",
            "Hand or finger ligament injuries",
            "Hand or finger nerve injuries",
            "Reconstructive hand surgery"
        ],
        "Hematologist": [
            "Unexplained fatigue",
            "Easy bruising",
            "Unexplained bleeding",
            "Frequent infections",
            "Enlarged lymph nodes",
            "Anemia symptoms",
            "Pale skin",
            "Shortness of breath",
            "Dizziness or lightheadedness",
            "Chest pain",
            "Blood clot symptoms",
            "Swollen spleen",
            "Unexplained weight loss",
            "Bone pain",
            "Joint pain or swelling",
            "Abnormal blood counts",
            "Myeloproliferative disorders",
            "Lymphoproliferative disorders",
            "Leukemia symptoms",
            "Multiple myeloma symptoms"
        ],
        "Hepatologist": [
            "Jaundice (yellowing of the skin and eyes)",
            "Abdominal pain",
            "Digestive issues",
            "Nausea or vomiting",
            "Unexplained weight loss",
            "Fatigue",
            "Enlarged liver",
            "Enlarged spleen",
            "Ascites (fluid accumulation in the abdomen)",
            "Edema (swelling)",
            "Dark urine",
            "Pale-colored stool",
            "Itchy skin",
            "Spider angiomas",
            "Hepatitis symptoms",
            "Cirrhosis symptoms",
            "Liver cancer symptoms",
            "Alcoholic liver disease",
            "Nonalcoholic fatty liver disease (NAFLD)",
            "Hepatic encephalopathy"
        ],
        "Hospitalist": [
            "Acute medical conditions",
            "Severe infections",
            "Heart failure exacerbation",
            "Respiratory distress or failure",
            "Uncontrolled diabetes",
            "Hypertensive crisis",
            "Severe gastrointestinal bleeding",
            "Renal failure",
            "Stroke or transient ischemic attack (TIA)",
            "Seizures or convulsions",
            "Severe trauma",
            "Postoperative complications",
            "Acute exacerbation of chronic conditions",
            "Dehydration",
            "Electrolyte imbalances",
            "Fever of unknown origin",
            "Altered mental status",
            "Sepsis",
            "Management of complex medical cases",
            "Coordination of care with specialists"
        ],
        "Hyperbaric Physician": [
            "Non-healing wounds",
            "Chronic diabetic foot ulcers",
            "Radiation-induced tissue damage",
            "Chronic non-healing surgical wounds",
            "Carbon monoxide poisoning",
            "Gas gangrene",
            "Necrotizing soft tissue infections",
            "Compromised skin grafts or flaps",
            "Chronic bone infections",
            "Crush injuries",
            "Severe anemia",
            "Sudden deafness",
            "Refractory osteomyelitis",
            "Delayed radiation injuries",
            "Arterial insufficiency ulcers",
            "Intracranial abscesses",
            "Thermal burns",
            "Near-drowning injuries",
            "Cyanide poisoning",
            "Air or gas embolisms"
        ],"Infectious Disease Specialist": [
            "Fever",
            "Chills",
            "Persistent cough",
            "Shortness of breath",
            "Sore throat",
            "Fatigue",
            "Muscle aches",
            "Headaches",
            "Nausea or vomiting",
            "Diarrhea",
            "Skin rashes",
            "Swollen lymph nodes",
            "Joint pain",
            "Night sweats",
            "Unexplained weight loss",
            "Urinary tract infections",
            "Respiratory infections",
            "Gastrointestinal infections",
            "Sexually transmitted infections",
            "Vector-borne infections"
        ],
        "Interventional Cardiologist": [
            "Chest pain or discomfort",
            "Shortness of breath",
            "Fatigue",
            "Palpitations",
            "High blood pressure",
            "Dizziness or fainting",
            "Swelling in the legs or ankles",
            "Irregular heartbeat",
            "Angina (heart-related chest pain)",
            "Heart attack symptoms",
            "Peripheral artery disease symptoms",
            "Coronary artery disease symptoms",
            "Valvular heart disease symptoms",
            "Heart murmurs",
            "Heart failure symptoms",
            "Cardiac arrhythmias",
            "Cardiac catheterization complications",
            "Stent-related issues",
            "Evaluation for coronary artery bypass surgery",
            "Cardiac rehabilitation needs"
        ],
        "Medical Examiner": [
            "Unexplained deaths",
            "Suspicious or violent deaths",
            "Autopsy analysis",
            "Postmortem examinations",
            "Identification of cause of death",
            "Determination of manner of death (homicide, suicide, accident, natural causes)",
            "Analysis of injuries and trauma",
            "Identification of toxins or drugs in the body",
            "Examination of skeletal remains",
            "Expert testimony in legal cases",
            "Documentation of injuries for legal purposes",
            "Evaluation of decomposed or mutilated bodies",
            "Identification of victims in mass disasters",
            "Child abuse investigations",
            "Documentation of evidence in criminal cases",
            "Consultation with law enforcement agencies",
            "Documentation of evidence for insurance claims",
            "Collaboration with other forensic specialists",
            "Analysis of firearm injuries",
            "Investigation of sudden or unexpected deaths"
        ],
        "Medical Geneticist": [
            "Family history of genetic disorders",
            "Multiple family members with the same genetic condition",
            "Congenital anomalies or birth defects",
            "Intellectual disabilities",
            "Developmental delays",
            "Autism spectrum disorders",
            "Inherited metabolic disorders",
            "Cystic fibrosis symptoms",
            "Hemophilia or other bleeding disorders",
            "Muscular dystrophy",
            "Neurofibromatosis",
            "Hereditary cancer syndromes",
            "Connective tissue disorders",
            "Rare genetic syndromes",
            "Genetic carrier screening",
            "Preconception counseling",
            "Prenatal genetic counseling",
            "Genetic testing and interpretation",
            "Hereditary heart conditions",
            "Genetic counseling for family planning"
        ],
        "Neonatologist": [
            "Preterm birth complications",
            "Low birth weight",
            "Breathing difficulties in newborns",
            "Jaundice in newborns",
            "Congenital anomalies or birth defects",
            "Infections in newborns",
            "Neonatal seizures",
            "Neonatal respiratory distress syndrome (RDS)",
            "Intrauterine growth restriction (IUGR)",
            "Persistent pulmonary hypertension of the newborn (PPHN)",
            "Feeding difficulties in newborns",
            "Neonatal abstinence syndrome (NAS)",
            "Neonatal jaundice",
            "Neonatal intensive care unit (NICU) admission",
            "Neonatal surgery needs",
            "Neonatal metabolic disorders",
            "Neonatal hematology issues",
            "Neonatal endocrinology issues",
            "Neonatal neurology issues",
            "Developmental follow-up for high-risk infants"
        ],
        "Nephrologist": [
            "Blood in urine",
            "Frequent urination",
            "Difficulty urinating",
            "High blood pressure",
            "Swelling in the legs or ankles",
            "Fatigue",
            "Foamy urine",
            "Unexplained weight loss",
            "Decreased urine output",
            "Kidney stones",
            "Kidney infections",
            "Proteinuria",
            "Electrolyte imbalances",
            "Chronic kidney disease symptoms",
            "Acute kidney injury",
            "Glomerulonephritis symptoms",
            "Polycystic kidney disease symptoms",
            "Nephrotic syndrome",
            "Hematuria",
            "Renal artery stenosis"
        ],
        "Neurodevelopmental Pediatrician": [
            "Speech and language delays",
            "Motor skill delays",
            "Social and emotional delays",
            "Learning difficulties",
            "Behavioral concerns",
            "Autism spectrum disorders",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Intellectual disabilities",
            "Genetic disorders affecting development",
            "Developmental regression",
            "Feeding difficulties",
            "Sleep disturbances",
            "School-related challenges",
            "Physical developmental delays",
            "Cerebral palsy",
            "Epilepsy in children",
            "Sensory processing issues",
            "Global developmental delay",
            "Neurodevelopmental disorders",
            "Family counseling and support"
        ],
        "Neurological Surgeon": [
            "Severe headaches",
            "Back or neck pain",
            "Numbness or tingling in limbs",
            "Muscle weakness",
            "Difficulty walking or coordination problems",
            "Seizures",
            "Tumors or masses in the brain or spine",
            "Cerebrovascular disorders",
            "Spinal cord injuries",
            "Degenerative spine conditions",
            "Traumatic brain injuries",
            "Hydrocephalus",
            "Peripheral nerve disorders",
            "Movement disorders (e.g., Parkinson's disease)",
            "Functional neurosurgery needs",
            "Spinal deformities",
            "Cranial or spinal congenital anomalies",
            "Neurovascular disorders",
            "Intractable pain syndromes",
            "Skull base tumors"
        ],"Neuromusculoskeletal Medicine Doctor": [
            "Muscle pain or weakness",
            "Joint pain or stiffness",
            "Back pain",
            "Neck pain",
            "Sciatica",
            "Carpal tunnel syndrome",
            "Sports injuries",
            "Tendinitis",
            "Bursitis",
            "Fibromyalgia",
            "Arthritis symptoms",
            "Myofascial pain syndrome",
            "Chronic pain conditions",
            "Soft tissue injuries",
            "Spinal disorders",
            "Muscle spasms",
            "Postural problems",
            "Nerve entrapment syndromes",
            "Musculoskeletal imbalances",
            "Repetitive strain injuries"
        ],
        "Neuropathologist": [
            "Memory loss",
            "Cognitive decline",
            "Neurological disorders",
            "Alzheimer's disease symptoms",
            "Parkinson's disease symptoms",
            "Huntington's disease symptoms",
            "Amyotrophic lateral sclerosis (ALS) symptoms",
            "Frontotemporal dementia",
            "Multiple sclerosis symptoms",
            "Neurodegenerative diseases",
            "Brain tumors",
            "Nerve injuries",
            "Peripheral neuropathy",
            "Neurological infections",
            "Prion diseases",
            "Neuromuscular disorders",
            "Cerebrovascular diseases",
            "Inflammatory neuropathies",
            "Toxic neuropathies",
            "Genetic neurological disorders"
        ],
        "Neuroradiologist": [
            "Headaches",
            "Seizures",
            "Dizziness or vertigo",
            "Numbness or tingling in limbs",
            "Visual disturbances",
            "Speech difficulties",
            "Balance problems",
            "Changes in behavior or personality",
            "Memory loss",
            "Cognitive decline",
            "Traumatic brain injuries",
            "Stroke symptoms",
            "Brain tumors",
            "Spinal cord injuries",
            "Neurodegenerative diseases",
            "Vascular malformations",
            "Multiple sclerosis lesions",
            "Cerebral aneurysms",
            "Intracranial hemorrhages",
            "Brain infections"
        ],
        "Nuclear Medicine Specialist": [
            "Thyroid disorders",
            "Bone pain",
            "Abnormalities in organ function",
            "Cancer staging and detection",
            "Cardiac stress testing",
            "Myocardial perfusion imaging",
            "Brain perfusion imaging",
            "Gastrointestinal bleeding",
            "Renal function evaluation",
            "Lung perfusion and ventilation scans",
            "Positron emission tomography (PET) scans",
            "Sentinel lymph node mapping",
            "Infection localization",
            "Radioactive iodine therapy",
            "Thyroid cancer imaging",
            "Liver and spleen imaging",
            "Bone scans",
            "Tumor metastasis detection",
            "Gallbladder function assessment",
            "Meckel's diverticulum evaluation"
        ],
        "Obstetrician": [
            "Missed periods",
            "Irregular menstrual cycles",
            "Abnormal bleeding",
            "Pregnancy confirmation",
            "Prenatal care",
            "High-risk pregnancy concerns",
            "Fetal development monitoring",
            "Gestational diabetes",
            "Preeclampsia symptoms",
            "Morning sickness",
            "Fetal movement monitoring",
            "Labor and delivery complications",
            "Postpartum issues",
            "Cesarean section delivery",
            "Vaginal birth after cesarean (VBAC) considerations",
            "Genetic counseling",
            "Multiple pregnancies (twins, triplets, etc.)",
            "Fertility concerns",
            "Family planning",
            "Birth control options"
        ],
        "Occupational Medicine Specialist": [
            "Work-related injuries",
            "Occupational exposures",
            "Repetitive strain injuries",
            "Ergonomic assessments",
            "Occupational health screenings",
            "Pre-employment physicals",
            "Workers' compensation cases",
            "Toxic substance exposures",
            "Hazardous material exposure",
            "Occupational lung diseases",
            "Hearing loss due to occupational noise",
            "Occupational stress-related issues",
            "Disability evaluations",
            "Fitness for duty assessments",
            "Return-to-work evaluations",
            "Workplace safety and health",
            "Job-related musculoskeletal disorders",
            "Occupational infections",
            "Environmental and occupational health risk assessments",
            "Occupational health education"
        ],
        "Orthopedic Surgeon": [
            "Joint pain",
            "Joint stiffness",
            "Swelling in joints",
            "Muscle weakness",
            "Back or neck pain",
            "Fractures or dislocations",
            "Torn ligaments or tendons",
            "Arthritis symptoms",
            "Carpal tunnel syndrome",
            "Sports injuries",
            "Orthopedic trauma",
            "Hip or knee pain",
            "Shoulder pain",
            "Spinal disorders",
            "Joint replacement surgery",
            "Minimally invasive orthopedic procedures",
            "Orthopedic oncology",
            "Pediatric orthopedic conditions",
            "Deformities or abnormalities",
            "Orthopedic rehabilitation needs"
        ],
        "Otolaryngologist (Head and Neck Surgeon)": [
            "Ear pain or discomfort",
            "Hearing loss",
            "Tinnitus (ringing in the ears)",
            "Vertigo or dizziness",
            "Sinus pain or congestion",
            "Nasal obstruction",
            "Nasal discharge",
            "Sore throat",
            "Hoarseness or voice changes",
            "Difficulty swallowing",
            "Thyroid nodules",
            "Thyroid disorders",
            "Head and neck cancers",
            "Facial trauma or fractures",
            "Salivary gland disorders",
            "Sleep apnea",
            "Snoring",
            "Allergies affecting the ears, nose, or throat",
            "Tonsil and adenoid issues",
            "Cleft lip and palate"
        ],"Pain Management Specialist": [
            "Chronic pain",
            "Back pain",
            "Neck pain",
            "Joint pain",
            "Muscle pain",
            "Neuropathic pain",
            "Fibromyalgia",
            "Arthritis pain",
            "Migraines or headaches",
            "Post-surgical pain",
            "Cancer-related pain",
            "Complex regional pain syndrome (CRPS)",
            "Painful diabetic neuropathy",
            "Shingles pain",
            "Pelvic pain",
            "Pain associated with autoimmune diseases",
            "Pain due to spine conditions",
            "Phantom limb pain",
            "Pain after trauma or injury",
            "Pain associated with psychological factors"
        ],
        "Palliative Medicine Specialist": [
            "Symptom management in serious illnesses",
            "Pain control in advanced diseases",
            "End-of-life care",
            "Hospice care",
            "Psychosocial support for patients and families",
            "Advance care planning",
            "Quality of life assessments",
            "Nausea and vomiting control",
            "Fatigue management",
            "Shortness of breath control",
            "Loss of appetite or weight loss management",
            "Counseling for emotional and spiritual concerns",
            "Coordination of care with other specialists",
            "Symptom management in chronic illnesses",
            "Spiritual and existential support",
            "Assistance with decision-making",
            "Family support and education",
            "Communication about treatment goals",
            "Crisis intervention and support",
            "Management of treatment side effects"
        ],
        "Pathologist": [
            "Biopsy analysis",
            "Tumor pathology",
            "Cytology assessments",
            "Autopsy analysis",
            "Blood smear analysis",
            "Bone marrow analysis",
            "Histopathology",
            "Clinical laboratory testing",
            "Molecular pathology",
            "Immunohistochemistry",
            "Flow cytometry",
            "Microbiology testing",
            "Hematology testing",
            "Blood bank services",
            "Infectious disease testing",
            "Genetic testing",
            "Diagnostic testing for organ diseases",
            "Cancer staging",
            "Identification of infectious agents",
            "Evaluation of genetic disorders"
        ],
        "Pediatric Allergist": [
            "Childhood allergies",
            "Food allergies",
            "Allergic rhinitis (hay fever)",
            "Asthma in children",
            "Eczema or atopic dermatitis",
            "Hives or urticaria",
            "Anaphylaxis",
            "Allergic conjunctivitis",
            "Contact dermatitis",
            "Insect sting allergies",
            "Medication allergies",
            "Latex allergies",
            "Allergic reactions to vaccines",
            "Immunodeficiency disorders",
            "Allergic skin conditions",
            "Allergic gastrointestinal disorders",
            "Evaluation of recurrent infections",
            "Diagnostic testing for allergies",
            "Patch testing for contact dermatitis",
            "Desensitization therapy for allergies"
        ],
        "Pediatric Cardiologist": [
            "Cyanosis (bluish skin color)",
            "Heart murmurs",
            "Congenital heart defects",
            "Irregular heartbeats",
            "Chest pain or discomfort",
            "Shortness of breath",
            "Fatigue",
            "Poor weight gain",
            "Feeding difficulties in infants",
            "Syncope (fainting)",
            "Palpitations",
            "High blood pressure in children",
            "Pediatric heart failure",
            "Rheumatic heart disease",
            "Infective endocarditis",
            "Kawasaki disease",
            "Cardiomyopathies in children",
            "Arrhythmias in children",
            "Aortic or pulmonary valve disorders",
            "Cardiac screening in high-risk children"
        ],
        "Pediatric Endocrinologist": [
            "Short stature",
            "Growth disorders",
            "Delayed puberty",
            "Early puberty",
            "Thyroid disorders in children",
            "Type 1 diabetes",
            "Type 2 diabetes",
            "Adrenal disorders in children",
            "Pituitary disorders in children",
            "Hormone imbalances",
            "Obesity in children",
            "Metabolic disorders in children",
            "Bone metabolism disorders",
            "Puberty disorders",
            "Genetic endocrine disorders",
            "Turner syndrome",
            "Klinefelter syndrome",
            "Congenital adrenal hyperplasia (CAH)",
            "Thyroid nodules in children",
            "Calcium and vitamin D disorders in children"
        ],
        "Pediatric Gastroenterologist": [
            "Abdominal pain",
            "Digestive issues",
            "Diarrhea",
            "Constipation",
            "Blood in stool",
            "Vomiting",
            "Reflux or GERD",
            "Inflammatory bowel disease (IBD) in children",
            "Irritable bowel syndrome (IBS) in children",
            "Celiac disease in children",
            "Food allergies in children",
            "Gastrointestinal bleeding in children",
            "Chronic liver diseases in children",
            "Pancreatic disorders in children",
            "Gastrointestinal infections in children",
            "Feeding difficulties in infants",
            "Malabsorption disorders in children",
            "Nutritional deficiencies in children",
            "Growth failure in children",
            "Gastrointestinal motility disorders in children"
        ],
        "Pediatric Hematologist": [
            "Unexplained anemia in children",
            "Easy bruising in children",
            "Unexplained bleeding in children",
            "Frequent infections in children",
            "Enlarged lymph nodes in children",
            "Splenomegaly (enlarged spleen) in children",
            "Hemophilia in children",
            "Sickle cell disease in children",
            "Thalassemia in children",
            "Leukemia in children",
            "Lymphoma in children",
            "Platelet disorders in children",
            "Neutropenia in children",
            "Bone marrow failure syndromes in children",
            "Hemoglobinopathies in children",
            "Coagulation disorders in children",
            "Immune thrombocytopenic purpura (ITP) in children",
            "Eosinophilia in children",
            "Hemolytic anemia in children",
            "Pediatric clotting disorders"
        ],"Pediatric Infectious Disease Specialist": [
            "Fever in children",
            "Recurrent infections in children",
            "Respiratory infections in children",
            "Gastrointestinal infections in children",
            "Skin infections in children",
            "Urinary tract infections in children",
            "Ear infections in children",
            "Meningitis in children",
            "Encephalitis in children",
            "Bone and joint infections in children",
            "Tuberculosis in children",
            "HIV/AIDS in children",
            "Congenital infections in newborns",
            "Vaccine-preventable diseases",
            "Vector-borne infections in children",
            "Parasitic infections in children",
            "Immunization-related concerns",
            "Travel-related infections in children",
            "Childhood vaccinations",
            "Infections in children with chronic illnesses"
        ],
        "Pediatric Nephrologist": [
            "Blood in urine in children",
            "Frequent urination in children",
            "Difficulty urinating in children",
            "High blood pressure in children",
            "Swelling in the legs or face in children",
            "Fatigue in children",
            "Foamy urine in children",
            "Unexplained weight loss in children",
            "Decreased urine output in children",
            "Kidney stones in children",
            "Urinary tract infections in children",
            "Proteinuria in children",
            "Electrolyte imbalances in children",
            "Chronic kidney disease in children",
            "Acute kidney injury in children",
            "Glomerulonephritis in children",
            "Polycystic kidney disease in children",
            "Nephrotic syndrome in children",
            "Hematuria in children",
            "Renal artery stenosis in children"
        ],
        "Pediatric Pulmonologist": [
            "Cough in children",
            "Wheezing in children",
            "Shortness of breath in children",
            "Chest pain in children",
            "Recurrent respiratory infections in children",
            "Asthma in children",
            "Bronchitis in children",
            "Pneumonia in children",
            "Cystic fibrosis in children",
            "Chronic cough in children",
            "Respiratory distress in infants",
            "Sleep-disordered breathing in children",
            "Interstitial lung diseases in children",
            "Congenital lung abnormalities in children",
            "Bronchiolitis in children",
            "Pulmonary hypertension in children",
            "Allergic rhinitis in children",
            "Foreign body aspiration in children",
            "Pulmonary function testing in children",
            "Ventilator management in children"
        ],
        "Pediatric Rheumatologist": [
            "Joint pain in children",
            "Joint swelling in children",
            "Morning stiffness in children",
            "Limping in children",
            "Fatigue in children",
            "Fever of unknown origin in children",
            "Skin rashes in children",
            "Eye redness or pain in children",
            "Unexplained weight loss in children",
            "Muscle weakness in children",
            "Recurrent fevers in children",
            "Lupus in children",
            "Juvenile idiopathic arthritis (JIA) in children",
            "Juvenile dermatomyositis in children",
            "Systemic sclerosis in children",
            "Vasculitis in children",
            "Kawasaki disease in children",
            "Autoinflammatory syndromes in children",
            "Periodic fever syndromes in children",
            "Pediatric musculoskeletal ultrasound"
        ],
        "Pediatric Surgeon": [
            "Congenital anomalies in newborns",
            "Gastrointestinal anomalies in children",
            "Thoracic anomalies in children",
            "Neonatal surgical emergencies",
            "Hernias in children",
            "Appendicitis in children",
            "Bowel obstruction in children",
            "Gastroesophageal reflux disease (GERD) in children",
            "Pediatric tumors or masses",
            "Pediatric trauma or injuries",
            "Abdominal pain in children",
            "Chest pain in children",
            "Inguinal disorders in children",
            "Anorectal malformations in children",
            "Pediatric laparoscopic surgery",
            "Pediatric thoracic surgery",
            "Pediatric oncology surgery",
            "Pediatric urologic surgery",
            "Pediatric plastic and reconstructive surgery",
            "Pediatric trauma surgery"
        ],
        "Pediatric Urologist": [
            "Urinary tract infections in children",
            "Bedwetting in children",
            "Voiding dysfunction in children",
            "Hydronephrosis in children",
            "Undescended testicles in children",
            "Hypospadias in children",
            "Kidney stones in children",
            "Bladder and kidney abnormalities in children",
            "Ureteropelvic junction (UPJ) obstruction in children",
            "Neurogenic bladder in children",
            "Hematuria in children",
            "Genitourinary trauma in children",
            "Urinary incontinence in children",
            "Vesicoureteral reflux (VUR) in children",
            "Pediatric urologic cancers",
            "Pediatric genital anomalies",
            "Pediatric laparoscopic urology",
            "Pediatric reconstructive urology",
            "Voiding dysfunction in children",
            "Urodynamic testing in children"
        ],
        "Perinatologist": [
            "High-risk pregnancies",
            "Multiple pregnancies (twins, triplets, etc.)",
            "Maternal medical conditions",
            "Maternal age-related concerns",
            "Preterm labor",
            "Preterm birth prevention",
            "Gestational diabetes",
            "Preeclampsia or eclampsia",
            "Maternal infections in pregnancy",
            "Fetal growth abnormalities",
            "Fetal anomalies or birth defects",
            "Amniotic fluid abnormalities",
            "Placental abnormalities",
            "Preconception counseling",
            "Genetic counseling",
            "Fetal monitoring",
            "Antenatal testing",
            "Intrauterine fetal surgery",
            "Fetal well-being assessments",
            "Maternal-fetal medicine consultations"
        ],"Physical Medicine and Rehabilitation Specialist": [
            "Muscle weakness",
            "Joint pain or stiffness",
            "Back or neck pain",
            "Neuropathic pain",
            "Balance problems",
            "Gait abnormalities",
            "Spinal cord injuries",
            "Amputations",
            "Sports injuries",
            "Stroke recovery",
            "Traumatic brain injuries",
            "Arthritis symptoms",
            "Repetitive strain injuries",
            "Post-surgical rehabilitation",
            "Neurological disorders",
            "Orthopedic injuries",
            "Chronic pain conditions",
            "Mobility issues",
            "Functional limitations",
            "Physical deconditioning"
        ],
        "Plastic Surgeon": [
            "Cosmetic surgery consultations",
            "Breast augmentation",
            "Breast reduction",
            "Breast lift",
            "Facelift",
            "Rhinoplasty",
            "Liposuction",
            "Tummy tuck (abdominoplasty)",
            "Body contouring",
            "Botox injections",
            "Dermal fillers",
            "Laser skin resurfacing",
            "Scar revision",
            "Burn reconstruction",
            "Hand surgery",
            "Cleft lip and palate repair",
            "Ear surgery (otoplasty)",
            "Reconstructive surgery",
            "Microsurgery",
            "Gender confirmation surgery"
        ],
        "Preventive Medicine Specialist": [
            "General health check-ups",
            "Immunizations",
            "Cancer screenings",
            "Cardiovascular risk assessment",
            "Cholesterol management",
            "Blood pressure management",
            "Diabetes prevention",
            "Weight management",
            "Nutrition counseling",
            "Exercise prescriptions",
            "Smoking cessation counseling",
            "Mental health screenings",
            "Sexual health screenings",
            "Osteoporosis prevention",
            "Infectious disease prevention",
            "Vaccination schedules",
            "Genetic risk assessments",
            "Health education and promotion",
            "Lifestyle modification counseling",
            "Occupational health and safety"
        ],
        "Psychiatrist (Child and Adolescent)": [
            "Behavioral problems in children",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Autism spectrum disorders",
            "Learning disabilities",
            "Anxiety disorders in children",
            "Depression in children",
            "Eating disorders in children",
            "Psychotic disorders in children",
            "Mood disorders in children",
            "Obsessive-compulsive disorder (OCD) in children",
            "Post-traumatic stress disorder (PTSD) in children",
            "Bipolar disorder in children",
            "Self-harm behaviors",
            "Suicidal ideation in children",
            "School-related issues",
            "Family relationship issues",
            "Social withdrawal",
            "Substance abuse in adolescents",
            "Grief and loss in children",
            "Parent-child conflict"
        ],
        "Pulmonologist": [
            "Cough",
            "Shortness of breath",
            "Chest pain",
            "Wheezing",
            "Chronic obstructive pulmonary disease (COPD)",
            "Asthma",
            "Bronchitis",
            "Pneumonia",
            "Interstitial lung disease",
            "Sleep apnea",
            "Lung cancer symptoms",
            "Pulmonary fibrosis",
            "Cystic fibrosis",
            "Lung infections",
            "Pulmonary hypertension",
            "Hemoptysis (coughing up blood)",
            "Respiratory failure",
            "Occupational lung diseases",
            "Allergic respiratory conditions",
            "Pleural effusion"
        ],
        "Radiation Oncologist": [
            "Cancer diagnosis",
            "Cancer staging",
            "Radiation therapy consultations",
            "Chemoradiotherapy",
            "Intensity-modulated radiation therapy (IMRT)",
            "Stereotactic radiosurgery",
            "Brachytherapy",
            "Prostate cancer treatment",
            "Breast cancer treatment",
            "Lung cancer treatment",
            "Head and neck cancer treatment",
            "Gastrointestinal cancer treatment",
            "Gynecologic cancer treatment",
            "Brain tumor treatment",
            "Bone cancer treatment",
            "Skin cancer treatment",
            "Soft tissue sarcoma treatment",
            "Pediatric cancer treatment",
            "Radiation therapy side effect management",
            "Palliative radiation therapy"
        ],
        "Reproductive Endocrinologist": [
            "Infertility",
            "Irregular menstrual cycles",
            "Polycystic ovary syndrome (PCOS)",
            "Endometriosis",
            "Recurrent pregnancy loss",
            "Ovulatory disorders",
            "Male infertility",
            "Premature ovarian insufficiency",
            "In vitro fertilization (IVF) consultations",
            "Egg freezing",
            "Sperm retrieval procedures",
            "Genetic screening in reproduction",
            "Donor egg or sperm options",
            "Surrogacy consultations",
            "Uterine factor infertility",
            "LGBTQ+ reproductive health",
            "Fertility preservation",
            "Hormone disorders affecting fertility",
            "Fertility treatment options",
            "Reproductive surgery"
        ],
        "Rheumatologist": [
            "Joint pain",
            "Joint swelling",
            "Morning stiffness",
            "Fatigue",
            "Fever",
            "Muscle pain",
            "Lupus symptoms",
            "Rheumatoid arthritis symptoms",
            "Spondyloarthropathy symptoms",
            "Osteoarthritis symptoms",
            "Gout symptoms",
            "Systemic sclerosis symptoms",
            "Sjogren's syndrome symptoms",
            "Vasculitis symptoms",
            "Myositis symptoms",
            "Antiphospholipid syndrome symptoms",
            "Mixed connective tissue disease symptoms",
            "Raynaud's phenomenon",
            "Ankylosing spondylitis symptoms",
            "Juvenile idiopathic arthritis symptoms"
        ],"Spinal Cord Injury Specialist": [
            "Paralysis",
            "Loss of sensation",
            "Impaired motor function",
            "Bowel or bladder dysfunction",
            "Spasticity",
            "Neuropathic pain",
            "Changes in reflexes",
            "Difficulty walking",
            "Muscle weakness",
            "Sexual dysfunction",
            "Respiratory issues",
            "Pressure sores",
            "Spinal fractures",
            "Vertebral dislocations",
            "Incomplete or complete spinal cord injury",
            "Autonomic dysreflexia",
            "Difficulty balancing",
            "Numbness or tingling",
            "Loss of coordination",
            "Difficulty with daily activities"
        ],
        "Sports Medicine Specialist": [
            "Sports injuries",
            "Muscle strains or sprains",
            "Joint injuries",
            "Tendon injuries",
            "Fractures or dislocations",
            "Concussions",
            "Overuse injuries",
            "ACL injuries",
            "Rotator cuff injuries",
            "Meniscus tears",
            "Stress fractures",
            "Tennis or golfer's elbow",
            "Shin splints",
            "Plantar fasciitis",
            "Muscle cramps or spasms",
            "Joint instability",
            "Sports-related back pain",
            "Heat-related illnesses",
            "Exercise-induced asthma",
            "Hydration and nutrition concerns"
        ],
        "Surgical Pathologist": [
            "Biopsy interpretation",
            "Tumor analysis",
            "Cancer staging",
            "Histopathology",
            "Cytopathology",
            "Immunohistochemistry",
            "Molecular pathology",
            "Frozen section interpretation",
            "Fine-needle aspiration (FNA) analysis",
            "Cytogenetic analysis",
            "In-situ hybridization",
            "Flow cytometry",
            "Hematopathology",
            "Breast pathology",
            "Gastrointestinal pathology",
            "Gynecologic pathology",
            "Head and neck pathology",
            "Lung pathology",
            "Genitourinary pathology",
            "Soft tissue pathology"
        ],
        "Thoracic Surgeon": [
            "Chest pain",
            "Shortness of breath",
            "Coughing up blood",
            "Lung nodules or masses",
            "Lung cancer",
            "Esophageal cancer",
            "Thymus tumors",
            "Pleural effusion",
            "Pneumothorax",
            "Diaphragmatic disorders",
            "Esophageal disorders",
            "Mediastinal tumors",
            "Chest wall tumors",
            "Lung infections",
            "Tracheal disorders",
            "Diaphragmatic hernia",
            "Pulmonary embolism",
            "Thoracic outlet syndrome",
            "Esophageal motility disorders"
        ],
        "Transplant Hepatologist": [
            "Liver cirrhosis",
            "Liver transplant evaluation",
            "Jaundice",
            "Ascites",
            "Hepatic encephalopathy",
            "Hepatitis B or C",
            "Alcoholic liver disease",
            "Nonalcoholic fatty liver disease (NAFLD)",
            "Autoimmune liver diseases",
            "Liver tumors",
            "Portal hypertension",
            "Liver biopsy interpretation",
            "Liver function abnormalities",
            "Acute liver failure",
            "Hemochromatosis",
            "Wilson's disease",
            "Primary biliary cholangitis (PBC)",
            "Primary sclerosing cholangitis (PSC)",
            "Biliary atresia",
            "Liver cysts or abscesses"
        ],
        "Trauma Surgeon": [
            "Multiple traumatic injuries",
            "Severe bleeding",
            "Fractures or dislocations",
            "Traumatic brain injuries (TBI)",
            "Spinal cord injuries",
            "Internal organ injuries",
            "Gunshot or stab wounds",
            "Crush injuries",
            "Burn injuries",
            "Orthopedic trauma",
            "Pelvic fractures",
            "Intra-abdominal injuries",
            "Chest injuries",
            "Head and neck trauma",
            "Soft tissue injuries",
            "Amputations",
            "Emergency surgery for trauma",
            "Reconstructive surgery for trauma",
            "Critical care management",
            "Emergency resuscitation"
        ],
        "Urologist": [
            "Blood in urine",
            "Frequent urination",
            "Painful urination",
            "Urinary incontinence",
            "Urinary tract infections (UTIs)",
            "Kidney stones",
            "Prostate issues",
            "Erectile dysfunction",
            "Testicular pain or lumps",
            "Bladder issues",
            "Overactive bladder",
            "Pelvic organ prolapse",
            "Urethral stricture",
            "Interstitial cystitis",
            "Hydrocele",
            "Varicocele",
            "Male infertility",
            "Sexual dysfunction",
            "Prostate cancer",
            "Bladder cancer"
        ],"Vascular and Interventional Radiologist": [
            "Peripheral arterial disease (PAD)",
            "Aneurysms",
            "Carotid artery disease",
            "Deep vein thrombosis (DVT)",
            "Pulmonary embolism",
            "Varicose veins",
            "Renal artery stenosis",
            "Vascular malformations",
            "Peripheral artery aneurysms",
            "Blood clots",
            "Hemodialysis access management",
            "Venous insufficiency",
            "Embolization procedures",
            "Angioplasty and stenting",
            "Thrombectomy procedures",
            "Vascular trauma",
            "Arteriovenous fistulas",
            "Vascular access complications",
            "Peripheral artery bypass grafts",
            "Vascular imaging and diagnostics"
        ],
        "Vascular Surgeon": [
            "Peripheral arterial disease (PAD)",
            "Aneurysms",
            "Carotid artery disease",
            "Deep vein thrombosis (DVT)",
            "Pulmonary embolism",
            "Varicose veins",
            "Renal artery stenosis",
            "Vascular malformations",
            "Peripheral artery aneurysms",
            "Blood clots",
            "Hemodialysis access management",
            "Venous insufficiency",
            "Embolization procedures",
            "Angioplasty and stenting",
            "Thrombectomy procedures",
            "Vascular trauma",
            "Arteriovenous fistulas",
            "Vascular access complications",
            "Peripheral artery bypass grafts",
            "Vascular imaging and diagnostics"
        ]
    }


        for specialist, symptoms in medical_symptoms.items():
            for symptom in symptoms:
                Symptom.objects.get_or_create(
                    name=symptom,
                    specialist=specialist
                )

        self.stdout.write(self.style.SUCCESS('Successfully populated symptoms table'))
