# Generated by Django 4.2.5 on 2023-10-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='alcohol_use',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='known_allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organ_donor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surgical_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tobacco_use',
        ),
        migrations.CreateModel(
            name='OutpatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('blood_pressure', models.CharField(help_text='Blood Pressure in mmHg, format: systolic/diastolic e.g., 120/80', max_length=10)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=4)),
                ('pulse_rate', models.PositiveIntegerField(help_text='Pulse rate in beats per minute')),
                ('respiratory_rate', models.PositiveIntegerField(help_text='Respiratory rate in breaths per minute')),
                ('oxygen_saturation', models.PositiveIntegerField(help_text='Oxygen saturation in percentage')),
                ('tobacco_use', models.BooleanField(default=False)),
                ('alcohol_use', models.BooleanField(default=False)),
                ('reason', models.TextField(help_text='Main reason for the visit')),
                ('medical_history', models.TextField(blank=True, help_text="Patient's past medical history")),
                ('surgical_history', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Current medications patient is taking')),
                ('allergies', models.TextField(blank=True, help_text='Known allergies')),
                ('physical_examination', models.TextField(default='Normal', help_text='Findings from physical examination')),
                ('diagnosis', models.TextField(help_text="Doctor's diagnosis based on the visit")),
                ('treatment_plan', models.TextField(blank=True, help_text='Recommended treatment plan')),
                ('follow_up_date', models.DateField(blank=True, help_text='Next scheduled visit, if any', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Any other notes or recommendations from the doctor')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.patient')),
            ],
        ),
    ]
