# Generated by Django 4.2.5 on 2023-10-08 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0003_remove_patient_alcohol_use_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('GW', 'General Ward'), ('SP', 'Semi Private'), ('PR', 'Private'), ('DL', 'Delux'), ('KD', "King's Delux")], max_length=2)),
                ('room_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_label', models.CharField(editable=False, max_length=5)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.room')),
            ],
        ),
    ]
