# Generated by Django 4.2.5 on 2023-10-10 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0004_room_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outpatientvisit',
            name='medications_prescribed',
            field=models.TextField(blank=True, help_text='Medication'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_label')},
        ),
        migrations.CreateModel(
            name='InpatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('reason_for_admission', models.TextField(help_text="Primary reason for the patient's admission.")),
                ('initial_diagnosis', models.TextField(blank=True, help_text='Initial diagnosis when the patient was admitted.', null=True)),
                ('final_diagnosis', models.TextField(blank=True, help_text='Final diagnosis upon discharge or during the course of treatment.', null=True)),
                ('medical_history', models.TextField(blank=True, help_text="Patient's past medical history.", null=True)),
                ('surgical_history', models.TextField(blank=True, help_text='Any surgeries or operations the patient has undergone in the past.', null=True)),
                ('medication_history', models.TextField(blank=True, help_text='List of medications the patient was on before admission.', null=True)),
                ('organ_donor', models.BooleanField(default=False)),
                ('tobacco_use', models.BooleanField(default=False)),
                ('alcohol_use', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, help_text='Any known allergies.', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Medications prescribed during the hospital stay.', null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Detailed treatment plan or procedures followed during the stay.', null=True)),
                ('complications', models.TextField(blank=True, help_text='Any complications that arose during the hospital stay.', null=True)),
                ('prognosis', models.TextField(blank=True, help_text="Doctor's prognosis upon discharge.", null=True)),
                ('follow_up_instructions', models.TextField(blank=True, help_text='Instructions for the patient to follow post-discharge.', null=True)),
                ('next_follow_up_date', models.DateField(blank=True, help_text='Date for the next follow-up visit, if scheduled.', null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or observations.', null=True)),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='backbone.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backbone.room')),
            ],
        ),
    ]
