# Generated by Django 4.2.5 on 2023-10-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0005_bed_is_occupied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inpatientvisit',
            name='room',
        ),
        migrations.AddField(
            model_name='inpatientvisit',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backbone.bed'),
        ),
    ]
