# Generated by Django 4.2.5 on 2023-10-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0006_remove_inpatientvisit_room_inpatientvisit_bed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inpatientvisit',
            unique_together={('patient', 'discharge_date')},
        ),
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('symptoms_presented', models.TextField(help_text='Symptoms observed or reported by the patient during the visit.')),
                ('physical_examination_results', models.TextField(blank=True, help_text='Results from the physical examination, e.g., heart rate, respiratory rate, etc.', null=True)),
                ('diagnosis', models.CharField(blank=True, help_text='Preliminary or final diagnosis given by the doctor.', max_length=255, null=True)),
                ('prescribed_medications', models.TextField(blank=True, help_text='Medications prescribed during the visit.', null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Detailed treatment plan or procedures to be followed.', null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('follow_up_recommendations', models.TextField(blank=True, null=True)),
                ('additional_instructions', models.TextField(blank=True, help_text='Any additional instructions given by the doctor to the patient.', null=True)),
                ('visit_duration', models.DurationField(blank=True, help_text="Duration of the doctor's visit.", null=True)),
                ('is_emergency', models.BooleanField(default=False, help_text='Indicates if the visit was due to an emergency situation.')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.doctor')),
                ('inpatient_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.inpatientvisit')),
            ],
        ),
    ]
