# Generated by Django 4.2.5 on 2023-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0008_department_lab_alter_inpatientvisit_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scantest',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
