# Generated by Django 4.2.5 on 2023-10-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0009_labtest_price_scantest_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='scantest',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
