# Generated by Django 4.2.5 on 2023-10-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backbone', '0011_patienttests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientTests',
            new_name='PatientTest',
        ),
    ]
