# Generated by Django 4.2.5 on 2023-10-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0015_alter_customer_last_name_alter_customer_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='backbone.patient'),
        ),
    ]
