# Generated by Django 4.2.5 on 2023-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0016_alter_customer_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='total_score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
