# Generated by Django 4.2.5 on 2023-11-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0017_doctor_total_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-room_type']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
    ]
