# Generated by Django 4.2.5 on 2023-11-12 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0020_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisit',
            name='visit_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inpatientvisit',
            name='admission_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='outpatientvisit',
            name='visit_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='test_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='DoctorWorkShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='backbone.doctor')),
            ],
            options={
                'ordering': ['day_of_week', 'shift_start_time'],
                'unique_together': {('doctor', 'day_of_week', 'shift_start_time', 'shift_end_time')},
            },
        ),
    ]
