# Generated by Django 4.2.5 on 2023-11-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0022_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatientvisit',
            name='was_emergency',
            field=models.BooleanField(default=False, help_text='Indicates if the visit was due to an emergency situation.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('GW', 'General Ward'), ('SP', 'Semi Private'), ('PR', 'Private'), ('DL', 'Delux'), ('KD', "King's Delux"), ('ICU', 'Intensive Care Unit')], max_length=3),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=200)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=12)),
                ('assisting_doctors', models.ManyToManyField(related_name='assisting_surgeries', to='backbone.doctor')),
                ('inpatient_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.inpatientvisit')),
                ('lead_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_surgeries', to='backbone.doctor')),
                ('operating_room', models.ForeignKey(limit_choices_to={'room_type': 'ICU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backbone.room')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.patient')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
