# Generated by Django 4.2.5 on 2023-11-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0023_inpatientvisit_was_emergency_alter_room_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='patient',
        ),
    ]
