# Generated by Django 4.2.5 on 2023-11-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0024_remove_surgery_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('GW', 'General Ward'), ('SP', 'Semi Private'), ('PR', 'Private'), ('DL', 'Delux'), ('KD', "King's Delux")], max_length=3),
        ),
    ]
