# Generated by Django 4.2.5 on 2023-11-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0025_room_price_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('RD', 'Ready'), ('MT', 'Maintenance'), ('DM', 'Damaged')], default='RD', max_length=2),
        ),
    ]
