# Generated by Django 4.2.5 on 2023-11-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0026_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='surgery',
            old_name='surgery_name',
            new_name='surgery_type',
        ),
        migrations.AddField(
            model_name='surgery',
            name='was_emergency',
            field=models.BooleanField(default=False, help_text='Indicates if the visit was due to an emergency situation.'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='operating_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backbone.icu'),
        ),
    ]
